raw frame sending PoC
medooze/media-server pull request #121
Opened 2022-07-13 19:45 UTC by mildsunrise

introduces functionality to send UDP messages as raw Ethernet frames directly through the interface, for a restricted subset of network configurations. for now we use the portable (but still Linux only) `AF_PACKET` interface to send frames.

this is the low-level part. the JS layer takes care of pulling most of the required parameters from the OS.

### Implementation details

- introduces a RawTxHandler object, which handles:
   - creating & setting up the socket
   - formatting the frame header, calculating checksums, etc.
   - sending frames

  it's constructed with a series of parameters and then offers a TrySend() method (analogous to EventLoop::Send) which attempts to send the UDP message as a raw frame. TrySend() can return false to signal that the packet should be sent
through the OS as normal.

- adds a SetRawTx() method to install this object in an endpoint, which causes the loop to attempt sending through it.

- adds ClearRawTx() and SetRawTx() methods to RTPBundleTransport which serve as wrappers to expose into JS

2022-07-15 10:20 UTC, murillo128 requested changes
I would prefer to move the socket handling to the EventLoop.

We would need to modify the fds poll set to from [socket,pipe] to [readsocket,writesocket,pipe].

If no raw tx is used readsocket == write socket, and if raw socket is set, replace it with the raw socket

2022-07-15 10:20 UTC, murillo128 commented on include/EventLoop.h
> +	void SetRawTx(std::optional<RawTxHelper>&& rawTx) {
Why optional and shared ptr? let's use an uniquee ptr instead

2022-07-15 10:20 UTC, murillo128 commented on include/RawTxHelper.h
> +class RawTxHelper
I would prefer the Helper to only do "helper" functions, i.e. handling the eth and udp header creation

2022-07-15 10:20 UTC, murillo128 commented on include/RawTxHelper.h
> +	uint32_t self_addr;
let's use camelCase consistently for class members

2022-07-15 10:20 UTC, murillo128 commented on src/EventLoop.cpp
> +	if (rawTx && rawTx->TrySend(ipAddr, port, std::move(packet)))
Why send it here and not just enque it and use the main loop for sending instead?

2022-07-15 10:20 UTC, murillo128 commented on src/RawTxHelper.cpp
> +	frame.ip.hdr_checksum = 0;
Let's move the checksum to an static member of IpHeader

2022-07-15 10:20 UTC, murillo128 commented on src/RawTxHelper.cpp
> +	frame.ip.hdr_checksum = ~checksum;
frame.ip.hdr_checksum = IpHeader::CalculcateChecksum(frame.ip);

2022-07-15 10:20 UTC, murillo128 commented on src/RawTxHelper.cpp
> +	union {
same here

2022-07-15 10:20 UTC, murillo128 commented on src/RawTxHelper.cpp
> +			throw std::system_error(std::error_code(errno, std::system_category()), "failed sending frame");
let's not throw but return false in error cases

2022-07-15 10:26 UTC, mildsunrise commented on include/EventLoop.h
> +	void SetRawTx(std::optional<RawTxHelper>&& rawTx) {
that still gets us the same problem. lambdas needs to be copyable (so we can pass as `std::function`), so that prevents you from capturing unique_ptrs inside them :(

2022-07-15 10:34 UTC, mildsunrise commented on src/RawTxHelper.cpp
> +			throw std::system_error(std::error_code(errno, std::system_category()), "failed sending frame");
this should ideally never happen. for now since this is a PoC, I'd prefer the server to terminate if there's an error (since that could indicate a bug) than silently discarding the error and sending the packet through the normal socket. for production I'm not sure how to handle this... we could uninstall the helper and/or print a warning, maybe. WDYT?

2022-07-15 10:51 UTC, mildsunrise commented on src/EventLoop.cpp
> +	if (rawTx && rawTx->TrySend(ipAddr, port, std::move(packet)))
there's the two reasons I didn't use `sendmmsg` for this (and instead do one sendmsg per frame)... one is that there's a [supposedly better approach](https://www.kernel.org/doc/html/latest/networking/packet_mmap.html) where you map a kernel ringbuffer into memory. packets are then enqueued (here) by placing them on the ringbuffer, and then (at the end of the loop iteration) you do a syscall to let the kernel know. the NIC takes them directly from there. this is as close as we can get to Netmap-style frameworks while remaining portable.

the other is just simplicity, this is a PoC and we may decide to add more functionality so I preferred to leave the optimization for later

2022-07-15 10:53 UTC, mildsunrise commented on src/RawTxHelper.cpp
> +	frame.ip.hdr_checksum = 0;
I think this comment is a duplicate of https://github.com/medooze/media-server/pull/121/files#r922025073?

2022-07-15 10:54 UTC, murillo128 commented on include/EventLoop.h
> +	void SetRawTx(std::optional<RawTxHelper>&& rawTx) {
Just use initialized capture:
```   
void SetRawTx(std::unique_tr<RawTxHelper>&& rawTx ) {
	Async([this, ptr = std::move(rawTxHelper)](auto &now) { this->rawTx = std::move(ptr); });
}
```

bw, don't use elipsis `...` for lambdas, I don't recall why, but it caused some ugly nasty issues that took me a while to debug.

2022-07-15 10:56 UTC, murillo128 commented on src/RawTxHelper.cpp
> +			throw std::system_error(std::error_code(errno, std::system_category()), "failed sending frame");
for production I typically log a warning and discard the packet silently

2022-07-15 11:09 UTC, mildsunrise commented on include/EventLoop.h
> +	void SetRawTx(std::optional<RawTxHelper>&& rawTx) {
regardless of how you initialize it, capturing a unique_ptr inside a lambda makes it noncopyable (because unique_ptrs are noncopyable) and we need the lambda to be copyable in order to pass it to `Async()`. see: https://taylorconor.com/blog/noncopyable-lambdas/

2022-07-15 11:14 UTC, mildsunrise commented on src/EventLoop.cpp
> +	if (rawTx && rawTx->TrySend(ipAddr, port, std::move(packet)))
yeah, the mmap approach looks like it fits nicely for us so it's an option to consider.
however I'm not sure the supposed benefits are really there, as I've read people claiming that packets are still copied from the mmap ringbuffer into an skb, so... how's it different than using sendmmsg? :sweat_smile: dunno.

in any case I'd agree with waiting a bit. then we can decide if we go directly to Netmap, to mmap or to sendmmsg, if any.

2022-07-15 11:14 UTC, mildsunrise commented on src/RawTxHelper.cpp
> +			throw std::system_error(std::error_code(errno, std::system_category()), "failed sending frame");
okay, we'll do that then

2022-07-15 12:04 UTC, murillo128 commented on include/EventLoop.h
> +	void SetRawTx(std::optional<RawTxHelper>&& rawTx) {
i get your point now, it is not about moving the pointer but moving the lambda. I think that could be solved by adding a `ASync`  method that takes a  `strd::function<void>(...)&&` as argument (or maybe not)

2022-07-15 12:31 UTC, murillo128 commented on include/EventLoop.h
> +	void SetRawTx(std::optional<RawTxHelper>&& rawTx) {
forget what I have just said.. I need to take some rest.. :)

2022-07-18 09:50 UTC, mildsunrise commented on include/EventLoop.h
> +	void SetRawTx(std::optional<RawTxHelper>&& rawTx) {
the helper is noncopyable, it contains a file descriptor. not sure we can duplicate AF_PACKET sockets

2022-07-18 09:52 UTC, murillo128 commented on include/EventLoop.h
> +	void SetRawTx(std::optional<RawTxHelper>&& rawTx) {
let's close this for now

2022-07-18 18:04 UTC, mildsunrise commented on src/RawTxHelper.cpp
> +	union {
done

2022-07-18 18:04 UTC, mildsunrise commented on src/RawTxHelper.cpp
> +	frame.ip.hdr_checksum = ~checksum;
done

2022-07-18 18:04 UTC, mildsunrise commented on include/RawTxHelper.h
> +	uint32_t self_addr;
done

2022-07-18 18:05 UTC, mildsunrise commented on src/RawTxHelper.cpp
> +			throw std::system_error(std::error_code(errno, std::system_category()), "failed sending frame");
done

2022-08-01 10:49 UTC, mildsunrise commented on include/RawTxHelper.h
> +class RawTxHelper
also done

2022-08-01 12:03 UTC, murillo128 commented
lgtm, I would do minor naming changes or refactoring of some structs, but it is purely cosmetic. Let's merge it.

2022-08-01 12:14 UTC, murillo128 approved these changes

2022-08-01 12:14 UTC, murillo128 commented on include/PacketHeader.h
> +	struct CandidateData {
Could we find a better name for this? like `ArpRoutingInfo` or similar? maybe good to move outside of the `PacketHeader` too

2022-08-01 12:14 UTC, murillo128 commented on include/PacketHeader.h
> +	using MacAddr = std::array<uint8_t, 6>;
Should we define it as a global type instead?

2022-08-01 12:14 UTC, murillo128 commented on include/PacketHeader.h
> +	static void InitHeader(PacketHeader& header, MacAddr selfLladdr, uint16_t port);
maybe do?

static PacketHeader Create( MacAddr selfLladdr, uint16_t port) instead, c++ will do copy elision.

2022-08-01 12:14 UTC, murillo128 commented on src/RTPBundleTransport.cpp
> +	PacketHeader header;
PacketHeader header = PacketHeader::Create( PacketHeader::ParseMac(selfLladdr), port); ?

2022-08-01 12:14 UTC, murillo128 commented on src/RTPBundleTransport.cpp
> +	PacketHeader::CandidateData fallbackData = { selfAddr, PacketHeader::ParseMac(gwLladdr) };
fallbackData -> defaultRoute ?

2022-08-01 12:14 UTC, murillo128 commented on src/RTPBundleTransport.cpp
> +			Send(candidate, std::move(buffer));
Much better!

2022-08-01 14:22 UTC, mildsunrise commented on include/PacketHeader.h
> +	struct CandidateData {
I tried putting it in different headers, but it created dependency loops. it seems a bit small-ish to put in its own header, too...

as for the name, `ArpRountingInfo` seems a bit misleading to me, is `FlowRoutingInfo` okay?

2022-08-01 14:24 UTC, mildsunrise commented on include/PacketHeader.h
> +	using MacAddr = std::array<uint8_t, 6>;
I'm usually against headers defining other things in the global namespace (other than the one with the same name), but if you're okay with making an exception, we can do that

2022-08-01 14:25 UTC, mildsunrise commented on include/PacketHeader.h
> +	static void InitHeader(PacketHeader& header, MacAddr selfLladdr, uint16_t port);
good point

2022-08-01 14:36 UTC, murillo128 commented on include/PacketHeader.h
> +	using MacAddr = std::array<uint8_t, 6>;
I am ok about adding a new .h for the `MacAddress` (less be verbose on naming.. :)

2022-08-01 14:42 UTC, mildsunrise commented on include/PacketHeader.h
> +	static void CalculateIpChecksum(PacketHeader& header);
I imagine this would apply to `PrepareHeader` below, as well? what should we do for `PrepareHeader`, do we make it a class method or do we have it take + return a PacketHeader?

2022-08-01 15:04 UTC, murillo128 commented on include/PacketHeader.h
> +	static void CalculateIpChecksum(PacketHeader& header);
class method better I think

2022-08-01 15:05 UTC, mildsunrise commented on include/PacketHeader.h
> +	static void CalculateIpChecksum(PacketHeader& header);
okay! now, this method can't be const since the checksum ifself needs to be zero while it's being calculated, do we make it a class method as well or something else?

2022-08-01 17:02 UTC, murillo128 commented on include/PacketHeader.h
> +	static void CalculateIpChecksum(PacketHeader& header);
we can make it a non-const method, maybe even extracting the internal checskum calculation to a helper funciton

2022-08-03 11:01 UTC, murillo128 requested changes

2022-08-03 11:01 UTC, murillo128 commented on src/EventLoop.cpp
> +					auto candidateData = item.rawTxData ? *item.rawTxData : this->rawTx->fallbackData;
auto&

2022-08-03 19:04 UTC, murillo128 commented on src/PacketHeader.cpp
> +	std::uniform_int_distribution<uint16_t> u16_distr;
no need to be random, let's use an atomic short instead

```
std::atomic_ushort identification;


void PacketHeader::PrepareHeader(PacketHeader& header, std::mt19937 rng, uint32_t ip, uint16_t port, CandidateData rawTxData, const Packet& payload)
{
        memcpy(header.eth.ether_dhost, rawTxData.dstLladdr.data(), 6);
        header.ip.src = htonl(rawTxData.selfAddr);
        header.ip.dst = htonl(ip);
        header.udp.dst = htons(port);
        header.udp.length = htons(sizeof(header.udp) + payload.GetSize());
        header.ip.totalLen = htons((sizeof(header) - sizeof(header.eth)) + payload.GetSize());
        header.ip.identification = htons(identification++);
        PacketHeader::CalculateIpChecksum(header);
        PacketHeader::CalculateUdpChecksum(header, payload);
}
```

2022-08-06 15:10 UTC, mildsunrise commented on src/PacketHeader.cpp
> +	memcpy(words, data, sizeof(words));
should move the type punning to every individual item, since apparently optimization of the memcpy isn't guaranteed for dynamically-sized arrays...

2022-08-06 15:50 UTC, mildsunrise commented on src/PacketHeader.cpp
> +	memcpy(words, data, sizeof(words));
the current code (with gcc 12.1, `-O3` and default march) vectorizes to a 9 instruction loop that processes 8 words at once:

~~~ asm
LOOP:
        movdqu  xmm0, XMMWORD PTR [CURSOR]
        add     CURSOR, 16
        movdqa  xmm3, xmm0
        punpckhwd       xmm0, xmm2
        punpcklwd       xmm3, xmm2
        paddd   xmm0, xmm3
        paddd   xmm1, xmm0
        cmp     END, CURSOR
        jne     LOOP
~~~

so it has asymptotic performance of 9/8 = 1.125 instructions / word.
if we need a bit more performance, we could unroll further to get (up to) 6/8 = 0.75 instructions / word.

Sergio mentioned [this article from igalia](https://blogs.igalia.com/dpino/2018/06/14/fast-checksum-computation/) which suggests working in bigger units, so I should try that as well :)

2022-08-08 12:54 UTC, mildsunrise commented on src/PacketHeader.cpp
> +	memcpy(words, data, sizeof(words));
I spent some time trying many things and was unable to get anything better than the current code.
Using bigger units as suggested in the article results in equal or worse code, and unrollings produce marginal (worse than expected) results.
Also, under AVX the above loop uses YMM regs and processes 16 words at a time, and unrolling seems to produce *worse* results.

I'll leave the current code with the following fixes:
- fix the type punning by doing it element by element (so the memcpy can be optimized away)
- add `__restrict__` to the `const void*` parameter to make sure compiler can optimize correctly
- make it into a separate `CheckSum` class

2022-09-06 07:26 UTC, murillo128 commented on include/EventLoop.h
> +		SendBuffer(uint32_t ipAddr, uint16_t port, std::optional<PacketHeader::CandidateData> rawTxData, Packet&& packet) :
`const std::optional<PacketHeader::CandidateData>& rawTxData` instead?

2022-09-06 07:45 UTC, murillo128 commented on include/RTPBundleTransport.h
> +	void SetRawTx(int32_t ifindex, unsigned int sndbuf, bool skipQdisc, const std::string& selfLladdr, uint32_t fallbackSelfAddr, const std::string& fallbackDstLladdr, uint16_t port);
what does de `Ll` in `selfLlAddr` means?

2022-09-06 08:28 UTC, mildsunrise commented on include/RTPBundleTransport.h
> +	void SetRawTx(int32_t ifindex, unsigned int sndbuf, bool skipQdisc, const std::string& selfLladdr, uint32_t fallbackSelfAddr, const std::string& fallbackDstLladdr, uint16_t port);
'lladdr' means 'link-level address' AFAIK. its named this way throughout the Linux APIs, so I thought I'd be consistent with them. but it's true that 'mac' would be more intuitive, so as you prefer

2022-09-07 08:44 UTC, mildsunrise commented on include/PacketHeader.h
> +	using MacAddr = std::array<uint8_t, 6>;
renamed and moved

2022-09-07 08:44 UTC, mildsunrise commented on src/RTPBundleTransport.cpp
> +	PacketHeader::CandidateData fallbackData = { selfAddr, PacketHeader::ParseMac(gwLladdr) };
renamed

2022-09-07 08:46 UTC, mildsunrise commented on include/PacketHeader.h
> +	struct CandidateData {
renamed

2022-09-07 08:59 UTC, mildsunrise commented on include/PacketHeader.h
> +	static void CalculateIpChecksum(PacketHeader& header);
made into a non-const method

2022-09-07 09:18 UTC, murillo128 commented on include/CheckSum.h
> +	inline void Calculate(const void* __restrict__ data, size_t size)
couldn't we use uint8_t*/char* instead of void*?

2022-09-07 09:19 UTC, murillo128 commented on include/MacAddress.h
> +	static MacAddress Parse(std::string str);
const std::string& str

2022-09-07 11:08 UTC, merged