Precheck corrupted vp8 packets
medooze/media-server pull request #143
Opened 2023-03-10 10:26 UTC by harryz2000

Corrupted packets would cause recording playback on web browser pause. These change is to precheck the vp8 frame header to drop the corrupted packet before going to next stage.

2023-03-10 18:14 UTC, murillo128 requested changes

2023-03-10 18:14 UTC, murillo128 commented on src/vp8/vp8depacketizer.cpp
> +#define AV_RL24(x) ((((const uint8_t*)(x))[2] << 16) | (((const uint8_t*)(x))[1] <<  8) | ((const uint8_t*)(x))[0])
use `get3`

2023-03-10 18:14 UTC, murillo128 commented on src/vp8/vp8depacketizer.cpp
> +static bool CheckFrameHeader(uint8_t* buf, size_t buf_size)
Isn't this the VP8PayloadHeder already in vp8.h?

2023-03-12 22:05 UTC, harryz2000 commented on src/vp8/vp8depacketizer.cpp
> +static bool CheckFrameHeader(uint8_t* buf, size_t buf_size)
Oh yes. Didn't know that. Will use that in case we still want to use this method. i.e if the sequence number could be used.

2023-03-13 10:16 UTC, harryz2000 commented on src/vp8/vp8depacketizer.cpp
> +#define AV_RL24(x) ((((const uint8_t*)(x))[2] << 16) | (((const uint8_t*)(x))[1] <<  8) | ((const uint8_t*)(x))[0])
Removed the code

2023-03-13 10:16 UTC, harryz2000 commented on src/vp8/vp8depacketizer.cpp
> +static bool CheckFrameHeader(uint8_t* buf, size_t buf_size)
Change to check first packet and sequence number. Removed this code.

2023-03-14 07:45 UTC, murillo128 commented on src/vp8/vp8.h
> +		firstPartitionSize	= get3(data, 0) >> 5;
My bad `get3` and `AVLR_24` has reverse byte order, maybe add a get3reversed or similar name in  tools.h

2023-03-14 07:51 UTC, murillo128 requested changes

2023-03-14 07:51 UTC, murillo128 commented on src/vp8/vp8depacketizer.h
> +		NONE,
Use snake camel for states; `None,Processing,Error`

2023-03-14 07:51 UTC, murillo128 commented on src/vp8/vp8depacketizer.cpp
> +			Error("-VP8Depacketizer::AddPacket() | Dropped invalid frame as start packet missed. timestamp: %lld\n", packet->GetTimestamp());
Use Warning instead of Error, Error is logged into the console logs by default, so this could be quite spammy on production.

2023-03-14 07:51 UTC, murillo128 commented on src/vp8/vp8depacketizer.cpp
> +	case State::NONE:
add 1 more ident

2023-03-14 07:51 UTC, murillo128 commented on src/vp8/vp8depacketizer.cpp
> +		if (desc.partitionIndex == 0 && desc.startOfPartition)
VP8 support multiple partitions per frame, this should not be an error

2023-03-14 07:51 UTC, murillo128 commented on src/vp8/vp8depacketizer.cpp
> +	if (currentTimestamp != frame.GetTimestamp())
Can we merge this timestamp check with the timestamp check in line 50?

2023-03-14 08:55 UTC, murillo128 commented
Also, can we add unit tests for this?

2023-03-14 09:56 UTC, harryz2000 commented on src/vp8/vp8.h
> +		firstPartitionSize	= get3(data, 0) >> 5;
Didn't notice either :( . Will fix.

2023-03-14 09:57 UTC, harryz2000 commented on src/vp8/vp8depacketizer.h
> +		NONE,
OK.

2023-03-14 09:57 UTC, harryz2000 commented on src/vp8/vp8depacketizer.cpp
> +			Error("-VP8Depacketizer::AddPacket() | Dropped invalid frame as start packet missed. timestamp: %lld\n", packet->GetTimestamp());
OK

2023-03-14 09:57 UTC, harryz2000 commented on src/vp8/vp8depacketizer.cpp
> +	case State::NONE:
OK

2023-03-14 09:58 UTC, harryz2000 commented on src/vp8/vp8depacketizer.cpp
> +		if (desc.partitionIndex == 0 && desc.startOfPartition)
It looks this is too strict. The suggestion from the RFC is the partition index SHOULD (not must) increase for each partition. Will remove.

2023-03-14 09:59 UTC, harryz2000 commented on src/vp8/vp8depacketizer.cpp
> +	if (currentTimestamp != frame.GetTimestamp())
Yes!

2023-03-14 09:59 UTC, harryz2000 commented
> 

Yes. We can add unit tests. Will do.

2023-03-17 14:48 UTC, murillo128 commented
lgtm

2023-03-17 14:49 UTC, merged