[draft] delay on arrival time
medooze/media-server pull request #167
Opened 2023-07-03 12:36 UTC by harryz2000

2023-07-03 20:56 UTC, murillo128 requested changes

2023-07-03 20:56 UTC, murillo128 commented on src/MediaFrameListenerBridge.cpp
> +			pendingPackets.emplace(schedued, std::pair<RTPPacket::shared, std::chrono::milliseconds>(packet,packetDuration));
I would prefer to enqueue directly to the packets and move the the code checing scheduled vs now to go inside the dispatch timer itself

2023-07-03 20:56 UTC, murillo128 commented on src/MediaFrameListenerBridge.cpp
> +		while (!pendingPackets.empty())
move this to the dispatch timer

2023-07-03 20:56 UTC, murillo128 commented on src/MediaFrameListenerBridge.cpp
> +			auto schedued = now + dispatchingDelayMs.load();
we need to make sure that the frames are dispatched in order, so in case the dispatchingDelay is lowered we don't have out of order packets.

2023-07-03 20:56 UTC, murillo128 commented on include/MediaFrameListenerBridge.h
> +	void SetDelayMs(std::chrono::milliseconds delayMs) { dispatchingDelayMs = delayMs; };
in stead of using atomic what we typically do is call timeService.Async() to set the delay. If the setDelay is happening on the timeService thread, there will cause no overhead and we will skip the atomic load in each media frame

2023-07-04 03:07 UTC, harryz2000 commented on src/MediaFrameListenerBridge.cpp
> +			auto schedued = now + dispatchingDelayMs.load();
Yes. Packets are put in the queue. Front packets would be always be dispatched earlier even they have a larger delay.

2023-07-04 03:07 UTC, harryz2000 commented on src/MediaFrameListenerBridge.cpp
> +			pendingPackets.emplace(schedued, std::pair<RTPPacket::shared, std::chrono::milliseconds>(packet,packetDuration));
Done

2023-07-04 03:07 UTC, harryz2000 commented on src/MediaFrameListenerBridge.cpp
> +		while (!pendingPackets.empty())
Done.

2023-07-04 03:08 UTC, harryz2000 commented on include/MediaFrameListenerBridge.h
> +	void SetDelayMs(std::chrono::milliseconds delayMs) { dispatchingDelayMs = delayMs; };
Done.

2023-07-04 08:23 UTC, murillo128 requested changes

2023-07-04 08:23 UTC, murillo128 commented on src/MediaFrameListenerBridge.cpp
> +			auto schedued = now + dispatchingDelayMs;
we should ensure that scheduled is increasing always, something like:

```
if (!packets.empty())
    scheduled = std::max(scheduled,packets.front().first+1);
```

2023-07-04 08:50 UTC, harryz2000 commented on src/MediaFrameListenerBridge.cpp
> +			auto schedued = now + dispatchingDelayMs;
Sure. Will do

2023-07-04 09:04 UTC, harryz2000 commented on src/MediaFrameListenerBridge.cpp
> +			auto schedued = now + dispatchingDelayMs;
Done. Assume you mean the packets.back(). Also move it out of the loop.

2023-07-05 07:58 UTC, murillo128 commented on include/MediaFrameListenerBridge.h
> +	std::queue<std::pair<std::chrono::milliseconds, std::pair<RTPPacket::shared, std::chrono::milliseconds>>> packets;
should we use a tuple instead? or maybe create a struct to avoid confusions.

2023-07-05 07:58 UTC, murillo128 commented on src/MediaFrameListenerBridge.cpp
> +		auto schedued = now + dispatchingDelayMs;
typo?

2023-07-05 08:02 UTC, murillo128 commented on src/MediaFrameListenerBridge.cpp
>  		{
do we really need this loop here now? I was emptying the queue when a new frame was received, but now that we are doing dispatching, we should probably move this to the dispatch method

2023-07-05 08:03 UTC, murillo128 commented on src/MediaFrameListenerBridge.cpp
> +			else if (accumulated > period)
is this condition ever meet?

2023-07-05 08:06 UTC, harryz2000 commented on include/MediaFrameListenerBridge.h
> +	std::queue<std::pair<std::chrono::milliseconds, std::pair<RTPPacket::shared, std::chrono::milliseconds>>> packets;
Sure. I will create a struct for it.

2023-07-05 08:06 UTC, harryz2000 commented on src/MediaFrameListenerBridge.cpp
> +		auto schedued = now + dispatchingDelayMs;
Yes. Will fix

2023-07-06 09:41 UTC, murillo128 approved these changes

2023-07-06 09:41 UTC, merged