Add FrameDispatchCoordinator class and tests
medooze/media-server pull request #170
Opened 2023-07-05 09:49 UTC by harryz2000

2023-07-06 09:44 UTC, murillo128 commented on src/FrameDispatchCoordinator.cpp
> +	auto delayMs = frameDelayCalculator.OnFrame(uint64_t(&listenerBridge), now, ts, clockRate);
use `listenerBridge.GetMediaSSRC()` we will need to make sure that the ssrcs are unique when constructing them on the SRT server

2023-07-06 10:07 UTC, murillo128 requested changes

2023-07-06 10:07 UTC, murillo128 commented on test/unit/TestFrameDispatchCoordinator.cpp
> +#include "FrameDispatchCoordinator.h"
can we change the test to be for the FrameDelayCalculator instead?

2023-07-06 23:19 UTC, harryz2000 commented on src/FrameDispatchCoordinator.cpp
> +	auto delayMs = frameDelayCalculator.OnFrame(uint64_t(&listenerBridge), now, ts, clockRate);
Sure.

2023-07-06 23:23 UTC, harryz2000 commented on test/unit/TestFrameDispatchCoordinator.cpp
> +#include "FrameDispatchCoordinator.h"
Yes. The current tests are actually for both FrameDispatchCoordinator (include FrameDelayCalculator)  and MediaFrameListenerBridge dispatching.  I will do a refactor to split some tests for FrameDelayCalculator and keep the tests for MediaFrameListenerBridge in the original test class.

2023-07-07 00:59 UTC, harryz2000 commented on test/unit/TestFrameDispatchCoordinator.cpp
> +#include "FrameDispatchCoordinator.h"
Done.

2023-07-07 01:00 UTC, harryz2000 commented on src/FrameDispatchCoordinator.cpp
> +	auto delayMs = frameDelayCalculator.OnFrame(uint64_t(&listenerBridge), now, ts, clockRate);
Done. The SrtConnection creates the audio and video listener bridge respectively with ssrc 1 and 2.

2023-07-07 07:04 UTC, merged