H265 SRT Recording/Packetizer bug
medooze/media-server pull request #174
Opened 2023-07-17 04:58 UTC by ZitaLiao

2023-07-17 04:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/medooze/media-server?pullRequest=174) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/medooze/media-server?pullRequest=174) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/medooze/media-server?pullRequest=174) it.</sub>

2023-07-17 07:41 UTC, murillo128 requested changes

2023-07-17 07:41 UTC, murillo128 commented on src/h265/H265Depacketizer.cpp
> +			const size_t nalAndFuHeadersLength = HEVCParams::RTP_NAL_HEADER_SIZE + HEVCParams::RTP_NAL_FU_HEADER_SIZE;
Please move this change to it's own PR

2023-07-17 09:36 UTC, ZitaLiao commented on src/h265/H265Depacketizer.cpp
> +			const size_t nalAndFuHeadersLength = HEVCParams::RTP_NAL_HEADER_SIZE + HEVCParams::RTP_NAL_FU_HEADER_SIZE;
Done.

2023-07-20 18:02 UTC, murillo128 commented
closed in favor of https://github.com/medooze/media-server/pull/178

2023-07-20 18:02 UTC, closed without merging