Draft: RTMP V1 implementation
medooze/media-server pull request #175
Opened 2023-07-17 06:19 UTC by harryz2000

2023-07-17 06:55 UTC, murillo128 requested changes

2023-07-17 06:55 UTC, murillo128 commented on include/rtmp/rtmpmessage.h
> +		VIDEO_TAG_HEADER,
Please use camel case

2023-07-17 06:55 UTC, murillo128 commented on src/rtmp/rtmppacketizer.cpp
> +template<typename DescClass, typename SPSClass, VideoCodec::Type codec>
I don't think this will work when we add support to AV1 as well, maybe it is easier to have an interface for the packetizer and derive each codec paketizer from it instead

2023-07-17 06:55 UTC, murillo128 commented on include/rtmp/rtmpmessage.h
> +	enum class RtmpVideoCodec {FLV1=2,SV=3,VP6=4,VP6A=5,SV2=6,AVC=7};
If it is not strictly necessary, revert the `enum class` to `enum` and the `RtmpVideoCodec` to `VideoCodec`.

While I acknowledge that current behavior is better, we have not changed the Audio classes, and there would be a completely mismatch between audio and video classes.

2023-07-17 07:01 UTC, harryz2000 commented on include/rtmp/rtmpmessage.h
> +		VIDEO_TAG_HEADER,
sure

2023-07-17 07:03 UTC, harryz2000 commented on src/rtmp/rtmppacketizer.cpp
> +template<typename DescClass, typename SPSClass, VideoCodec::Type codec>
No. It wouldn't support AV1 I think. Will have a further look.

2023-07-17 07:04 UTC, harryz2000 commented on include/rtmp/rtmpmessage.h
> +	enum class RtmpVideoCodec {FLV1=2,SV=3,VP6=4,VP6A=5,SV2=6,AVC=7};
Just worried about the same value representing different types. But should not be a problem to revert them to enum. Will do.

2023-07-17 07:07 UTC, harryz2000 commented on include/rtmp/rtmpmessage.h
> +	VideoCodec::Type GetGenericVideoCodec() const
This is for the packetizer to check the RTMPVideoFrame's codec, which is using VideoCodec enum defined in codecs.h .

2023-07-17 07:29 UTC, harryz2000 commented on include/rtmp/rtmpmessage.h
> +	VideoCodec::Type GetGenericVideoCodec() const
OK

2023-07-24 08:49 UTC, murillo128 requested changes

2023-07-24 08:49 UTC, murillo128 commented on include/rtmp/objectparser.h
> +	std::pair<bool, size_t> Parse(uint8_t* data, size_t len)
This `Parse` method doesn't parse anything, what does it do?

2023-07-24 08:49 UTC, murillo128 commented on src/rtmp/rtmpmessage.cpp
> +#include <cassert>
remove include

2023-07-24 08:49 UTC, murillo128 commented on include/rtmp/objectparser.h
> +	std::pair<bool, size_t> Parse(uint8_t* data, size_t len)
Seems that this class is just writting to a buffer, use https://github.com/medooze/libdatachannels/blob/master/src/internal/BufferWritter.h instead

2023-07-25 03:01 UTC, harryz2000 commented on include/rtmp/objectparser.h
> +	std::pair<bool, size_t> Parse(uint8_t* data, size_t len)
This is to make it easy to parse chunked data for a object (currently fixed-size, could be extended to support variable-size object as well). 

You could see it is not a complicated class and it doesn't look to me the BufferWritter has the facility to try to fill as much as possible data, which means we would need to check its capacity and current data size to put in the buffer. But using ObjectParser is make it easier as if data is enough for the object, no data would be put in.

The initial thought was the ObjectParser would be a base class for different parsers, such as SI24Parser, ExtraDataParser, etc. However, I found probably for now it is enough just use the base class (to reduce code). But I kept the name. For example:

```
class SI24Parser : public ObjectParser
{
public:
      SI24Parser() : ObjectParser(3) {}

      uint32_t GetValue() { return (int32_t(get3(buffer.data(), 0)) << 8) >> 8; }
}
```

2023-07-25 17:01 UTC, murillo128 requested changes

2023-07-26 07:29 UTC, murillo128 requested changes

2023-07-26 07:29 UTC, murillo128 commented on src/rtmp/rtmpmessage.cpp
> +				bufferWritter = std::make_unique<BufferWritter>(dataBuffer.data(), dataBuffer.size());
can't we use `extraData` directly?

2023-07-26 07:29 UTC, murillo128 commented on src/rtmp/rtmpmessage.cpp
> +				codecEx = VideoCodecEx(FourCcToUint32(dataBuffer.begin()));
let's add a new `BYTE fourCC[4];` member and use the memory directly

2023-07-26 07:54 UTC, harryz2000 commented on src/rtmp/rtmpmessage.cpp
> +				codecEx = VideoCodecEx(FourCcToUint32(dataBuffer.begin()));
Done.

2023-07-26 08:07 UTC, murillo128 requested changes

2023-07-26 08:07 UTC, murillo128 commented on include/avcdescriptor.h
> +	BYTE GetNumOfVideoParameterSets()		const { return 0;	}
remove (see later comment)

2023-07-26 08:19 UTC, harryz2000 commented on src/rtmp/rtmppacketizer.cpp
> +		for (int i=0;i<desc.GetNumOfVideoParameterSets();i++)
How do you think to check the type? Using std::enable_if?

2023-07-26 08:29 UTC, murillo128 commented on src/rtmp/rtmppacketizer.cpp
> +		for (int i=0;i<desc.GetNumOfVideoParameterSets();i++)
std::is_same ? https://en.cppreference.com/w/cpp/types/is_same

2023-07-26 09:03 UTC, harryz2000 commented on src/rtmp/rtmppacketizer.cpp
> +		for (int i=0;i<desc.GetNumOfVideoParameterSets();i++)
I am not sure std::is_same could work directly for this case, as we have to prevent the code compile when the type is not expected. I think we might have to add override functions such as below. Are you OK with this or do you have other thoughts?

```
void AddVps(DWORD nalUnitLength, BYTE* nalHeader, const AVCDescriptor&desc, VideoFrame* frame)
{
}

void AddVps(DWORD nalUnitLength, BYTE* nalHeader, const HEVCDescriptor&desc, VideoFrame* frame)
{
	for (int i=0;i<desc.GetNumOfVideoParameterSets();i++)
	{
		//Set size
		setN(nalUnitLength, nalHeader, 0, desc.GetVideoParameterSetSize(i));
		
		//Append nal size header
		frame->AppendMedia(nalHeader, nalUnitLength);
		
		//Append nal
		auto ini = frame->AppendMedia(desc.GetVideoParameterSet(i),desc.GetVideoParameterSetSize(i));
		
		//Crete rtp packet
		frame->AddRtpPacket(ini,desc.GetVideoParameterSetSize(i),nullptr,0);
	}	
}
```

2023-07-26 12:13 UTC, murillo128 approved these changes

2023-07-26 12:13 UTC, merged