Fix crash caused by RTMPConnection shared_from_this
medooze/media-server pull request #182
Opened 2023-07-28 01:34 UTC by harryz2000

2023-07-28 06:32 UTC, murillo128 requested changes
How do you think the segmentation is happening?

The only way I can see it from happening is if `End()` is called before the thread is started and it dosen't wait for the thread to end.  But in this case all the Run() instructions would be using garbage mem for this.

2023-07-28 06:32 UTC, murillo128 commented on src/rtmp/rtmpconnection.cpp
> +		Run(connection);
no need to pass the connection to the Run command, the `connection` shared_ptr should be alive during the whole life of the lamda execution.

2023-07-28 06:32 UTC, murillo128 commented on src/rtmp/rtmpconnection.cpp
> +	thread = std::thread([=, connection=shared_from_this()](){
rename to `self` (that's what we use in other parts of the code similar to this)

2023-07-28 06:59 UTC, harryz2000 commented on src/rtmp/rtmpconnection.cpp
> +		Run(connection);
The issue is if the thread is executed during destructor, the shared_ptr is not available.

2023-07-28 07:07 UTC, harryz2000 commented on src/rtmp/rtmpconnection.cpp
> +		Run(connection);
This is an example that would throw:
```
#include <memory>

class Test : public std::enable_shared_from_this<Test>
{
public:
    ~Test()
    {
        auto a = shared_from_this();
    }
};


int main()
{
    auto b = std::make_shared<Test>();
    return 0;
}
```

2023-07-28 07:11 UTC, harryz2000 commented on src/rtmp/rtmpconnection.cpp
> +	thread = std::thread([=, connection=shared_from_this()](){
Done.

2023-07-28 09:21 UTC, murillo128 commented on src/rtmp/rtmpconnection.cpp
> +		Run(connection);
It makes sense, good catch!

2023-07-28 09:36 UTC, murillo128 requested changes

2023-07-28 09:36 UTC, murillo128 commented on src/rtmp/rtmpconnection.cpp
> +		Run(self);
I don't think we need to pass `self` to the `Run()` method, as it is being captured in the lambda, also should we try to get a weak reference instead to prevent leaking?

2023-07-28 09:36 UTC, murillo128 commented on src/rtmp/rtmpconnection.cpp
> +		Run(self);
like 

```
thread = std::thread([=, weak=std::weak_ptr<RTMPConnection>(shared_from_this())](){
                //Check if the shared pointer is still valid
                auto self = weak.lock();
                //If connection has already ended
                if (!self)
                      //Exit
                      return;
		//Block signals to avoid exiting on SIGUSR1
		blocksignals();
		//Run
		Run();
          });
````

2023-07-28 09:36 UTC, murillo128 commented on src/rtmp/rtmpconnection.cpp
> +		Run(self);
Although in this case we wouldn't be calling the `onDisconnect` callback, so probably just better to do

```
//Start thread and run, hold reference to us to prevent being destroyed before Run ends.
thread = std::thread([=, self=shared_from_this()](){
		//Block signals to avoid exiting on SIGUSR1
		blocksignals();
		//Run
		Run();
          });
```

2023-07-28 10:20 UTC, harryz2000 commented on src/rtmp/rtmpconnection.cpp
> +		Run(self);
> like
> 
> ```
> thread = std::thread([=, weak=std::weak_ptr<RTMPConnection>(shared_from_this())](){
>                 //Check if the shared pointer is still valid
>                 auto self = weak.lock();
>                 //If connection has already ended
>                 if (!self)
>                       //Exit
>                       return;
> 		//Block signals to avoid exiting on SIGUSR1
> 		blocksignals();
> 		//Run
> 		Run();
>           });
> ```

Yes. This would skip the onDisconnect, which should not what we want.

2023-07-28 10:39 UTC, harryz2000 commented on src/rtmp/rtmpconnection.cpp
> +		Run(self);
> ```
> //Start thread and run, hold reference to us to prevent being destroyed before Run ends.
> thread = std::thread([=, self=shared_from_this()](){
> 		//Block signals to avoid exiting on SIGUSR1
> 		blocksignals();
> 		//Run
> 		Run();
>           });
> ```

I think this one works same as passing the the shared_ptr to Run() function. I am not sure which is better. Passing it as argument looks more explicit to me. But I am fine to change to this.

2023-07-28 10:46 UTC, harryz2000 commented on src/rtmp/rtmpconnection.cpp
> +		Run(self);
Done.

2023-07-28 11:42 UTC, harryz2000 commented on src/rtmp/rtmpconnection.cpp
> +		Run(self);
By the way, about the leaking concern. The lambda would be destroyed once the thread is stopped, so is the shared_ptr. And I tested the RTMPConnection could be destroyed. The only thing would be the End() call in the destructor wouldn't be too much useful as the thread must be stopped so it could be released.

2023-07-31 07:43 UTC, murillo128 approved these changes

2023-07-31 07:43 UTC, merged