Ensure timer callback wouldn't be called after destruction
medooze/media-server pull request #183
Opened 2023-07-31 11:49 UTC by harryz2000

2023-07-31 12:04 UTC, harryz2000 commented
I think it would be ideal the TimerService (EventLoop) could provide a "synced" "cancel" function to have something similar to set "timerCancelled" flag so after the cancel, the callback wouldn't be executed.

2023-07-31 12:49 UTC, murillo128 requested changes

2023-07-31 12:49 UTC, murillo128 commented on src/MediaFrameListenerBridge.cpp
> +		timerCancelled = true;
You can do this instead:

```
timeService.Sync([this](auto){
    dispatchTimer->Cancel();
})
```

Given that the both the timer lamba and the dispatch timer cancelation will be run on the EventLoop thread, there is no need for the `timerCancelled` flag. 

Also, better move this to the `Stop()` call to prevent a race condition between the `MediaFrameListener` destructor and the `EventLoop` destructor (being js garbage collected objects we can't ensure the disposal order)

2023-07-31 13:02 UTC, murillo128 commented on src/MediaFrameListenerBridge.cpp
> +		timerCancelled = true;
something like

```
void MediaFrameListenerBridge::Stop()
{
	Debug("-MediaFrameListenerBridge::Stop() [this:%p]\n", this);

	timeService.Sync([=](auto now) {
                //Dispatch pendingREADY packets now
		std::vector<RTPPacket::shared> pending;		
		while (packets.size())
		{
			//Add to pending packets
			pending.push_back(packetInfo.packet);
			//remove it from pending packets
			packets.pop();
		}
		//Dispatch RTP packets
		Dispatch(pending);

                //Updated last dispatched 
		lastSent = now;

		//Cancel dispatch timer
                dispatchTimer->Cancel();

		//TODO wait onMediaFrame end
		for (auto listener : listeners)
			listener->onEnded(this);
		//Clear listeners
		listeners.clear();

                //Flag for not schedulin the dispatch timer again
                stopped = true;                
	});
}
```

we should also check for the `stopped` flag just before:
https://github.com/medooze/media-server/blob/34a56ba708735e1bc1538e453fd7a7a44a4154c2/src/MediaFrameListenerBridge.cpp#L149

2023-08-01 00:18 UTC, harryz2000 commented on src/MediaFrameListenerBridge.cpp
> +		timerCancelled = true;
Done as suggested. 

Still think having a function like `CancelRemoveCallbacks() `would be handy. But not a priority.

2023-08-01 05:47 UTC, murillo128 requested changes

2023-08-01 05:47 UTC, murillo128 commented on src/MediaFrameListenerBridge.cpp
> +	Stop();
don't call Stop()  in the destructor, there is no warranty that the EventLoop will be alive at this time (because of js garbage collection)

2023-08-01 05:55 UTC, harryz2000 commented on src/MediaFrameListenerBridge.cpp
> +	Stop();
If that is case, should we pass a shared_ptr<TimeService> instead? Or keep the TimeService live during MediaFrameListenerBridge? This uncertainty seems not ideal.

Plus, if MediaFrameListenerBridge is released but TimeService is not, would the stop() call be guaranteed by other code before the release? Otherwise, it might still have the crash issue.

2023-08-01 05:58 UTC, harryz2000 commented on src/MediaFrameListenerBridge.cpp
> +	Stop();
If the Stop() would be called before destruction, this stop() call wouldn't cause any issue as it would return immediately.

2023-08-01 10:14 UTC, murillo128 approved these changes

2023-08-01 10:14 UTC, murillo128 commented on src/MediaFrameListenerBridge.cpp
> +	Stop();
i didn't saw the check in the `Stop()` method, lgtm now.

2023-08-01 10:15 UTC, merged