Static analysis: various defects
medooze/media-server pull request #199
Opened 2023-09-05 00:29 UTC by harryz2000

Potential nullptr use, divide by zero, incorrect count calculation, always false condition, etc

2023-09-05 00:41 UTC, mildsunrise commented
the two diffs under `src/rtp` are huge, could it be because of line endings?

2023-09-05 00:45 UTC, harryz2000 commented
Yeah. I also found it. Looks like a merge issue. I am fixing it.

2023-09-05 01:07 UTC, harryz2000 commented
Yes. It turns out the line ending of these files are CRLF (different with others) in the repository. I manually changed these two files to be CRLF and it appears working now. 

We should unify the line endings one day IMO.

2023-09-05 05:16 UTC, murillo128 commented on src/aac/aacconfig.h
> +		for (DWORD i=0;i<sizeof(rates)/sizeof(rates[0]);i++)
should we change `rates` to an std::array better?

2023-09-06 01:52 UTC, harryz2000 commented on src/aac/aacconfig.h
> +		for (DWORD i=0;i<sizeof(rates)/sizeof(rates[0]);i++)
I am OK for both. But change to std::array, which seems more modern.

2023-09-06 04:22 UTC, murillo128 requested changes

2023-09-06 04:22 UTC, murillo128 commented on src/aac/aacconfig.h
> +	static constexpr std::array<DWORD, 13> rates = {
I don't think that the `13` is needed

2023-09-06 04:28 UTC, harryz2000 commented on src/aac/aacconfig.h
> +	static constexpr std::array<DWORD, 13> rates = {
The std::array needs two template arguments. Using one doesn't compile.

2023-09-06 04:34 UTC, murillo128 approved these changes

2023-09-06 04:34 UTC, merged