Static analysis: trivial format specifier, return value check, etc
medooze/media-server pull request #200
Opened 2023-09-05 01:09 UTC by harryz2000

2023-09-05 02:47 UTC, harryz2000 commented on src/DTLSICETransport.cpp
> -	return (len>=0);
Note, len is always >= 0 here.

2023-09-05 05:13 UTC, murillo128 requested changes

2023-09-05 05:13 UTC, murillo128 commented on src/DTLSICETransport.cpp
> +		( lost>0 ||  (group->GetCurrentLost() && (now-source->lastNACKed)/1000>std::max(rtt,uint32_t(20))))
i prefer `std::max<uint32_t>(rtt,20);` or `std::max<rtt,20u>;` not sure which one of the 3 is more correct

2023-09-05 05:13 UTC, murillo128 commented on src/h264/H264LayerSelector.cpp
> +	nextTemporalLayerId = 0;
delete from constructor as they are in .h

2023-09-05 05:13 UTC, murillo128 commented on src/avcdescriptor.cpp
> +		(void)sps.Decode(spsData[i],spsSizes[i]);
change by `if (sps.Decode(...`

2023-09-05 06:00 UTC, harryz2000 commented on include/rtmp/rtmpclientconnection.h
> +		TransType type {};
Tried to give it a zeroed value since as long as it has a certain value it wouldn't cause strange issues. Would change to an valid value, which probably better for readibility.

2023-09-05 06:00 UTC, harryz2000 commented on include/rtp/RTCPPayloadFeedback.h
> +	FeedbackType feedbackType {};
As above. Will change.

2023-09-05 06:11 UTC, harryz2000 commented on src/avcdescriptor.cpp
> +		(void)sps.Decode(spsData[i],spsSizes[i]);
Yeah. Agree. Considered that but kept no change for keeping the change trivial. Would fix then.

2023-09-05 06:17 UTC, murillo128 commented on include/rtmp/rtmpclientconnection.h
> +		TransType type {};
We should probably either remove any constructor that doesn't set the TransType or add an Unknown TransType

2023-09-06 01:55 UTC, harryz2000 commented on include/CPUMonitor.h
> +	bool		started = false;
Done

2023-09-06 02:07 UTC, harryz2000 commented on include/rtmp/rtmpclientconnection.h
> +		TransType type {};
Removed the default constructor, which seems not very useful

2023-09-06 02:18 UTC, harryz2000 commented on src/h264/H264LayerSelector.cpp
> +	nextTemporalLayerId = 0;
OK

2023-09-06 03:04 UTC, harryz2000 commented on src/DTLSICETransport.cpp
> +		( lost>0 ||  (group->GetCurrentLost() && (now-source->lastNACKed)/1000>std::max(rtt,uint32_t(20))))
both looks OK. Preferred 20u one as it is shorter.

2023-09-06 04:37 UTC, murillo128 approved these changes

2023-09-06 04:37 UTC, merged