Fix static analysis errors relevant to video codecs
medooze/media-server pull request #220
Opened 2023-10-09 07:30 UTC by harryz2000

2023-10-09 08:40 UTC, murillo128 requested changes

2023-10-09 08:40 UTC, murillo128 commented on src/h264/h264encoder.cpp
> +	curNal = 0;
can we move it to the .h instead?

2023-10-09 08:40 UTC, murillo128 commented on src/vp8/vp8encoder.cpp
> +	pic	= NULL;
can we move it to the .h instead?

2023-10-09 08:40 UTC, murillo128 commented on src/h264/h264encoder.cpp
> +	memset(&pic, 0, sizeof(pic));
`pic = {}` in .h instead?

2023-10-09 08:40 UTC, murillo128 commented on include/VideoDecoderWorker.h
> +	pthread_t thread = 0;
nullptr or {} better?

2023-10-09 10:32 UTC, harryz2000 commented on src/vp8/vp8encoder.cpp
> +	pic	= NULL;
I tried to make small change and keep the initialisation consistent with existing code. Would you like to change the existing code as well? Sometimes the change would be big and probably not be convenient for review.

2023-10-09 10:48 UTC, harryz2000 commented on include/VideoDecoderWorker.h
> +	pthread_t thread = 0;
As mentioned in another pr. pthread_t is an integer, seems 0 is more suitable

2023-10-09 10:52 UTC, harryz2000 commented on src/h264/h264encoder.cpp
> +	memset(&pic, 0, sizeof(pic));
Yes. We can. As mentioned in another response, how should we resolve this as existing code does initialisation in cpp file. Which way should we take?
1. moving all initialisation to header file, including existing code
2. Only add initialisation for missing ones, don't change existing ones
3. Keep the missing ones consistent with existing code
I am fine to either way.

2023-10-09 12:17 UTC, murillo128 commented on src/h264/h264encoder.cpp
> +	memset(&pic, 0, sizeof(pic));
The code may be bigger, but the complexity is low. So let's modernize it and go with 3.

2023-10-09 22:09 UTC, harryz2000 commented on src/h264/h264encoder.cpp
> +	memset(&pic, 0, sizeof(pic));
I assume you meant: Make all initialisation consistent and in header file. I will change to that way. Please let me know if my understanding is correct.

2023-10-09 22:19 UTC, murillo128 commented on src/h264/h264encoder.cpp
> +	memset(&pic, 0, sizeof(pic));
that's correct

2023-10-09 22:41 UTC, harryz2000 commented on src/h264/h264encoder.cpp
> +	curNal = 0;
Done

2023-10-09 22:41 UTC, harryz2000 commented on src/vp8/vp8encoder.cpp
> +	pic	= NULL;
Done

2023-10-09 22:41 UTC, harryz2000 commented on src/h264/h264encoder.cpp
> +	memset(&pic, 0, sizeof(pic));
Done.

2023-10-10 05:29 UTC, harryz2000 commented on src/h264/h264encoder.cpp
> +	memset(&pic, 0, sizeof(pic));
Actually let me double check whether {} has same effect as memset. The {} does eliminate the Coverity errors.

2023-10-10 05:49 UTC, harryz2000 commented on src/h264/h264encoder.cpp
> +	memset(&pic, 0, sizeof(pic));
Yes. My tests indicated it does zero the struct.

2023-10-10 08:49 UTC, murillo128 approved these changes
lgtm

2023-10-10 08:49 UTC, merged