[W.I.P.] Coverity fix: catch MP4V2 exception so pointer/resource would not leak
medooze/media-server pull request #223
Opened 2023-10-13 03:59 UTC by ZitaLiao

2023-10-18 12:36 UTC, murillo128 commented
@harryz2000 could we try to use `unique_ptr` to manage the leaked resources instead?

2023-10-19 02:14 UTC, harryz2000 commented
Yes. Using unique_ptr would be a good idea. Will change.

2023-10-19 02:29 UTC, harryz2000 commented
Yes. That would be a good idea. Will make the change.

2023-10-19 11:49 UTC, murillo128 commented on src/mp4streamer.cpp
> +	return desc.release();
let's make `MP4Streamer::GetAVCDescriptor()` return a `std::unique_ptr` and chante the rtmpmp4streamer to use a unique ptr too

2023-10-19 11:51 UTC, murillo128 commented on src/mp4recorder.cpp
> +					videoTrack = videoTrackPtr.release();
I think that we should modernize the whole pointer management of the tracks. So let's change the `videoTracks` to be a vector of `shared_ptr`s and use shared_ptrs instead of unique_ptrs for `videoTrack` so the code here is easier to change

2023-10-19 11:52 UTC, murillo128 requested changes
soory for changin my mind, but let's try to modernize the whole file

2023-10-22 09:56 UTC, murillo128 commented on src/rtmp/rtmpmp4stream.cpp
> +	desc = streamer.GetAVCDescriptor().release();
can we make `desc`  in in RTMPMP4Stream a unique ptr too?

2023-10-22 22:38 UTC, harryz2000 commented on src/rtmp/rtmpmp4stream.cpp
> +	desc = streamer.GetAVCDescriptor().release();
It seems this rtmpmp4stream.cpp wasn't used in any build files. Therefore, I tented to do minor changes in case the change would break anything. Basically I didn't optimize this file. Where was this file used? Or should we optimize it? If so, we might want to add it to some cmake file to at least verify it can compile.

2023-10-23 06:32 UTC, murillo128 commented on src/rtmp/rtmpmp4stream.cpp
> +	desc = streamer.GetAVCDescriptor().release();
ok, let's ignore it for now.

2023-10-23 06:32 UTC, murillo128 approved these changes
lgtm

2023-10-23 06:32 UTC, merged