Set RTT to streams. RTT is only checked once for now.
medooze/media-server pull request #228
Opened 2023-11-23 10:10 UTC by harryz2000

2023-11-23 10:47 UTC, murillo128 requested changes
minor change required, lgtm otherwise

2023-11-23 10:47 UTC, murillo128 commented on src/rtmp/rtmpconnection.cpp
> +					pthread_mutex_lock(&mutex);
can we use range for loops instead?

2023-11-23 23:26 UTC, harryz2000 commented on src/rtmp/rtmpconnection.cpp
> +					pthread_mutex_lock(&mutex);
Yes. Done

2023-11-28 07:31 UTC, murillo128 approved these changes
lgtm

2023-11-28 07:31 UTC, merged