Add timestamp checker
medooze/media-server pull request #232
Opened 2023-11-30 07:19 UTC by harryz2000

2023-12-01 09:17 UTC, murillo128 requested changes

2023-12-01 09:17 UTC, murillo128 commented on include/TimeStampChecker.h
> +	static constexpr uint32_t MaxDurationDiffMs = 3000;
this should be a configurable parameter on the constructor of `TimeStampChecker`

2023-12-01 09:17 UTC, murillo128 commented on include/TimeStampChecker.h
> +	static constexpr uint32_t MaxDurationDiffMs = 3000;
Also, please add a brief description of what does this class do

2023-12-01 09:20 UTC, murillo128 requested changes

2023-12-01 09:20 UTC, murillo128 commented on include/TimeStampChecker.h
> +	CheckResult Check(const MediaFrame &frame)
If it is a timestamp checked, pass the timestamps as input, not the whole frame

2023-12-12 07:35 UTC, murillo128 commented on include/TimeStampChecker.h
> +		auto durationOnTs = (timestamp - lastTimeStamp) * 1000 / clock;
either auto is an int64, and then we have propblems if timestamp - lastTimestamp value is too big, or it is and uint64_t and we have problems when timestamp < lastTimestamp.

2023-12-12 07:51 UTC, harryz2000 commented on include/TimeStampChecker.h
> +		auto durationOnTs = (timestamp - lastTimeStamp) * 1000 / clock;
Yes. Missed this one. Will change to get the diff for whichever is larger.

2023-12-12 08:29 UTC, harryz2000 commented on include/TimeStampChecker.h
> +		auto durationOnTs = (timestamp - lastTimeStamp) * 1000 / clock;
Changed to use a function to always get positive diff.

2024-01-18 23:26 UTC, harryz2000 commented
The issue wasn't reproduced in new dev server versions. Close for now.

2024-02-15 10:50 UTC, murillo128 approved these changes
lgtm

2024-02-15 10:50 UTC, merged