Parse AV1 OBU in case dependency descriptor is not present for resolution stats
medooze/media-server pull request #239
Opened 2024-01-03 11:41 UTC by harryz2000

2024-01-03 21:30 UTC, harryz2000 commented on src/DependencyDescriptorLayerSelector.cpp
> +#include "av1/AV1.h"
I tried to use conditions in the class for AV1. But yes, using a separate class would be cleaner.

2024-01-04 07:55 UTC, murillo128 requested changes

2024-01-04 07:55 UTC, murillo128 commented on src/av1/AV1LayerSelector.cpp
> +	auto info = GetObuInfo(reader.PeekData(), obuSize);
we would need to refactor this into ObuInfo::Parse to be consistent with the rest of the objects

2024-01-04 07:55 UTC, murillo128 commented on src/av1/AV1LayerSelector.cpp
> +	auto info = GetObuInfo(reader.PeekData(), obuSize);
In the refactor, we should pass the reader, so we don't have to store the `payload` pointer on the `ObuInfo`

2024-01-04 07:55 UTC, murillo128 commented
lgtm, we can merge and do the refactor in an upcoming PR

2024-01-04 07:55 UTC, merged