bitstream: fixes
medooze/media-server pull request #257
Opened 2024-02-22 23:07 UTC by mildsunrise

fixes several issues in bitstream.h (BitReader and BitWriter):

 - in C++, [it is undefined behavior to do `dword >> 32` or `dword << 32`](https://stackoverflow.com/a/18918340/710951). And we are doing that in several points of the code. This is one of the UBs that hardly leads to crashes, but it did lead to an actual bug, which is observed in #253 (see description). In `Get()`, when we combine cache with ret:

   https://github.com/medooze/media-server/blob/6b369a170791bf25f80b056e6f83855e5a5e6291/include/bitstream.h#L91

   This assumes that the lower bits of `cached` are zero. Which is guaranteed since `SkipCached()` does a right shift:

   https://github.com/medooze/media-server/blob/6b369a170791bf25f80b056e6f83855e5a5e6291/include/bitstream.h#L268

   Except when `n` is 32, in which case this invokes UB. In most implementations / architectures this will result in leaving `cache` unchanged rather than zeroed.

 - `GetVariableLengthUnsigned` makes no sense. It is an AV1 primitive (essentially identical to H.264 `ue(v)`) and it should be implemented as: 
![Screenshot from 2024-02-22 21-29-42](https://github.com/medooze/media-server/assets/1177304/eac2b2eb-881a-4c0a-a844-9a77011b9906)

 - `Get()` doesn't set error condition if there are not enough bits to read (or rather, it only does that in specific cases).

2024-02-22 23:28 UTC, mildsunrise commented
More issues that I have:

- `GolombExpDecoder::Decode()` invokes UB with certain user input.
- `BitWritter::Put()` does not signal error if there isn't enough space in buffer (at least, not immediately).
- It is possible to underflow `cached`, for example by reading more bits than present. this can then cause `Left()` to underflow as well.

2024-02-23 07:45 UTC, murillo128 requested changes

2024-02-23 07:45 UTC, murillo128 commented on include/bitstream.h
> +			if (cached<a)
shouldn't this check be done inside `GetChached()` ?

2024-02-23 07:45 UTC, murillo128 commented on include/bitstream.h
>  		cached -= n;
shouldn't we check that `n <= cached`?

2024-02-23 07:45 UTC, murillo128 commented on include/bitstream.h
> +			if (!n) return v;
should we put this check on the else?

2024-02-23 07:45 UTC, murillo128 commented on include/bitstream.h
>  		} else {
```suggestion
		} else if (n) {
```

2024-02-23 16:37 UTC, mildsunrise commented on include/bitstream.h
> +			if (cached<a)
`GetCached()` is called from two places, and only this call site needs the check. but if you prefer to move it there for clarity, we can do that too

2024-02-23 16:38 UTC, mildsunrise commented on include/bitstream.h
>  		cached -= n;
this is the issue I pointed above (It is possible to underflow cached, for example by reading more bits than present), so yeah let's fix that too

2024-02-23 16:43 UTC, mildsunrise commented on include/bitstream.h
> +			if (!n) return v;
the idea was to skip the FlushCache() call afterwards, but yes, we can also do that if you prefer

2024-02-23 16:45 UTC, mildsunrise commented on include/bitstream.h
>  		cached -= n;
applied

2024-02-23 18:09 UTC, murillo128 commented on include/bitstream.h
> +			if (cached<a)
better do it in the inner most layer always

2024-02-23 18:09 UTC, murillo128 commented on include/bitstream.h
> +			if (!n) return v;
we can put it at the begginging of the function, or as a first clause of the if-else-if

2024-02-23 18:11 UTC, murillo128 approved these changes
lgtm with just to minor comments, feel free to merge it when you are confortable with it

2024-06-03 02:59 UTC, bcostdolby commented
Overall this class makes some basic assumptions on its usage that are not enforced which seems to allow these kinds of issues (especially if needing to decode some kind of variable amount of bits).

It seems there is an "error" state on the class which seems to be its way of notifying issues to the caller. Should we also set that in all these cases (in addition to preventing UB)?

I would think we need to enforce the value passed to this is always <=32 in general for all the public functions.

For example even the Get() does a:
ret = cache >> (32 - n)

if n is given as larger than 32 this is also UB.


I would suggest a common check maybe for all public functions (seems they are all public) for places like:
* Get(n) : Where n > 32
* Check(n) : Where n > 32 (I guess covered by the get, but still)
and others...:
* Skip(n)
* Peek(n)
* SkipCached() 
* GetCached()

seems we are good at checking n == 0 but not n > 32.

2024-06-03 03:01 UTC, bcostdolby commented
Also GetNonSymmetric() could probably use some comments describing what it is trying to do. The name doesnt really tell us much.

2024-06-03 05:53 UTC, bcostdolby requested changes
I added comments to overall ticket, this class needs more changes I think. Actually reading through the comments, it seems Alba identified some of these but maybe they were not pushed?

2024-08-27 13:56 UTC, mildsunrise commented
many of the tasks described in the comments of this PR, as well as outstanding comments in diffs, have been addressed now.

I'll make a list of the ones that haven't been addressed yet (please everyone verify I'm not missing anything):

- GolombExpDecoder::Decode() invokes UB with certain user input
- BitWritter::Put() does not signal error if there isn't enough space in buffer (at least, not immediately)
- check for n>32 in Check() too, requested by @bcostdolby (actually I'd change all these checks into asserts :smiling_imp: but I understand if others don't wanna)
- GetNonSymmetric() could probably use some comments describing what it is trying to do

some questions:

> It seems there is an "error" state on the class which seems to be its way of notifying issues to the caller. Should we also set that in all these cases (in addition to preventing UB)?

regarding this, I think we should do the opposite, and convert this file to use exceptions. not sure how others see it

in any case, I'd merge this now and we can open a new PR for further fixes.
also, @bcostdolby you mentioned you added things to "overall ticket", which ticket is that?

2024-08-27 13:59 UTC, murillo128 approved these changes
lgtm, let's do the rest of the fixes in a different PR. Probably also introduce exceptions.

2024-08-27 13:59 UTC, merged

2024-08-27 18:07 UTC, murillo128 commented
+1 to replace error flags by proper exception handling.

Not sure about asserts, I would be worried about crashing on production
because a software bug.

El mar, 27 ago 2024, 15:57, Alba Mendez ***@***.***> escribió:

> many of the tasks described in the comments of this PR, as well as
> outstanding comments in diffs, have been addressed now.
>
> I'll make a list of the ones that haven't been addressed yet (please
> everyone verify I'm not missing anything):
>
>    - GolombExpDecoder::Decode() invokes UB with certain user input
>    - BitWritter::Put() does not signal error if there isn't enough space
>    in buffer (at least, not immediately)
>    - check for n>32 in Check() too, requested by @bcostdolby
>    <https://github.com/bcostdolby> (actually I'd change all these checks
>    into asserts 😈 but I understand if others don't wanna)
>    - GetNonSymmetric() could probably use some comments describing what
>    it is trying to do
>
> some questions:
>
> It seems there is an "error" state on the class which seems to be its way
> of notifying issues to the caller. Should we also set that in all these
> cases (in addition to preventing UB)?
>
> regarding this, I think we should do the opposite, and convert this file
> to use exceptions. not sure how others see it
>
> in any case, I'd merge this now and we can open a new PR for further fixes.
> also, @bcostdolby <https://github.com/bcostdolby> you mentioned you added
> things to "overall ticket", which ticket is that?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/medooze/media-server/pull/257#issuecomment-2312640776>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAIFN43XO65M5PMSMOCRI2DZTSAUFAVCNFSM6AAAAABDVZTDX2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGMJSGY2DANZXGY>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>