Passing SSRC, fixed the frame time, threading
medooze/media-server pull request #266
Opened 2024-03-04 04:04 UTC by harryz2000

2024-03-05 07:47 UTC, murillo128 commented on include/SimulcastMediaFrameListener.h
> +	void Push(std::shared_ptr<VideoFrame>&& frame);
why do we need a `shared_ptr` ?

2024-03-05 07:52 UTC, harryz2000 commented on include/SimulcastMediaFrameListener.h
> +	void Push(std::shared_ptr<VideoFrame>&& frame);
Because now the Push function was called in the TimeService::Async, which accept an std::function as argument. Unfortunately, to cast to std::function, the object needs to be copy-able. The std::unique_ptr is not copy-able. Another option could be to templatize the Async function, which would be a quite big change and probably not feasible at this point.

2024-03-05 07:59 UTC, harryz2000 commented on include/SimulcastMediaFrameListener.h
> +	void Push(std::shared_ptr<VideoFrame>&& frame);
Using a raw pointer when passing to the lambda (then std::function) would also compile. However, it would potentially cause memory leak.

2024-03-05 09:15 UTC, murillo128 requested changes

2024-03-05 09:15 UTC, murillo128 commented on src/MediaFrameListenerBridge.cpp
> +	cloned->SetSSRC(ssrc);
if `MediaFrame::Clone` doesn't clone the SSRC, please fix it instead

2024-03-05 09:15 UTC, murillo128 commented on src/VideoPipe.cpp
> +			resized->SetTime(videoBuffer->HasTime() ? videoBuffer->GetTime() : getTime());
Please add a different PR

2024-03-05 09:15 UTC, murillo128 commented on src/SimulcastMediaFrameListener.cpp
> +	timeService.Async([this, cloned = std::move(cloned)](std::chrono::milliseconds) mutable {
If you need to make sure that the `Push` method is called in the `timeService` thread, better move the `timeService.Async` method inside the `Push`method

2024-03-05 10:46 UTC, harryz2000 commented on src/SimulcastMediaFrameListener.cpp
> +	timeService.Async([this, cloned = std::move(cloned)](std::chrono::milliseconds) mutable {
OK

2024-03-05 10:49 UTC, harryz2000 commented on src/MediaFrameListenerBridge.cpp
> +	cloned->SetSSRC(ssrc);
Right. Will check.

2024-03-05 22:49 UTC, harryz2000 commented on src/VideoPipe.cpp
> +			resized->SetTime(videoBuffer->HasTime() ? videoBuffer->GetTime() : getTime());
Actually this has to be fixed so that the SimulcastMediaFrameListener could work. Do you still prefer to have a separate PR?

2024-03-07 01:58 UTC, harryz2000 commented on src/MediaFrameListenerBridge.cpp
> +	cloned->SetSSRC(ssrc);
The SSRC here is not using the frame's own ssrc. I fixed the clone() function. However, still need to manually set here.

2024-03-07 02:00 UTC, harryz2000 commented
@murillo128 This PR is dependency of other PRs. Are you OK for this one?

2024-03-07 11:36 UTC, murillo128 commented on src/VideoPipe.cpp
> +			resized->SetTime(videoBuffer->HasTime() ? videoBuffer->GetTime() : getTime());
I think it is better to not have "jumbo" commits, so it is not about the PR itself but having lots of changes into a single commit,

2024-03-07 11:45 UTC, murillo128 commented on src/MediaFrameListenerBridge.cpp
> +	timeService.Async([=, frame = std::move(cloned)] (auto now){
I see,  maybe it is better to refector a bit to avoid the impresion that it is a problem in the `Clone()` function but that we need to override the ssrc of the incoming ssrc to the oitgoing ssrc
```suggestion
	timeService.Async([=, frame = std::shared_ptr<MediaFrame>(frame.Clone())] (auto now){
		//Update outgoing ssrc before multiplexing
		frame->SetSSRC(ssrc);
```

2024-03-08 07:34 UTC, murillo128 approved these changes
lgtm

2024-03-11 22:35 UTC, merged