Only update stats when resolution is valid
medooze/media-server pull request #280
Opened 2024-05-13 05:16 UTC by harryz2000

This avoid the stats being overwritten by frames whose resolution is not set

2024-05-13 06:16 UTC, bcostdolby commented on src/MediaFrameListenerBridge.cpp
> +				width = videoFrame->GetWidth();
Why is there no width/height in the first place? 

Concept of change lgtm but surprised it is necessary or even visible. Most video frames have resolution on them so even if one or two of them didnt would probably not see that. I would expect other things to be broken as well unless there are special no-video video frames that exist I dont know about.

2024-05-13 06:24 UTC, harryz2000 commented on src/MediaFrameListenerBridge.cpp
> +				width = videoFrame->GetWidth();
The resolution was parsed from current frame data. Not all frame data contain width/height. i.e. it might be only the key frame that contains width/heigh information. We could set frame resolution to be same as one of the previous frames, which would be similar as current way to set the stats.

2024-05-13 06:34 UTC, harryz2000 commented on src/MediaFrameListenerBridge.cpp
> +				width = videoFrame->GetWidth();
Actually I can set the width here if it is not valid, which should be no harm. Will add some extra code.

2024-05-20 06:33 UTC, murillo128 requested changes

2024-05-20 06:33 UTC, murillo128 commented on src/MediaFrameListenerBridge.cpp
> +				videoFrame->SetWidth(width);
I am not sure we should be modifying the VideoFrame object at all, note that it is not "owned" by the MediaFrameListenerBridge

2024-05-20 06:37 UTC, harryz2000 commented on src/MediaFrameListenerBridge.cpp
> +				videoFrame->SetWidth(width);
Right. I can remove this frame setting. It wouldn't impact current fix and it seems fine it is not set on the frame.

2024-05-29 07:04 UTC, murillo128 requested changes

2024-05-29 07:04 UTC, murillo128 commented on src/MediaFrameListenerBridge.cpp
> +					width = video->GetWidth();
As we have removed setting the width/height on the video frames, we need to use the packet info instead
```suggestion
					width = packet->GetWidth();
```

2024-05-29 07:04 UTC, murillo128 commented on src/MediaFrameListenerBridge.cpp
> +					height = video->GetHeight();
```suggestion
					height = packet->GetHeight();
```

2024-05-31 00:39 UTC, harryz2000 commented on src/MediaFrameListenerBridge.cpp
> +					height = video->GetHeight();
Indeed.

2024-05-31 00:46 UTC, harryz2000 commented
@murillo128 Please have another look. I think it is good for merge now. thx

2024-06-17 15:02 UTC, murillo128 approved these changes
lgtm

2024-06-17 23:05 UTC, merged