DIOS-4552 fix pic rescale rounding issue and unit test
medooze/media-server pull request #283
Opened 2024-05-13 23:01 UTC by yezhan10

2024-05-13 23:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/medooze/media-server?pullRequest=283) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/medooze/media-server?pullRequest=283) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/medooze/media-server?pullRequest=283) it.</sub>

2024-05-15 04:00 UTC, bcostdolby requested changes

2024-05-15 21:46 UTC, yezhan10 commented on src/VideoPipe.cpp
> +		videoWidth = ((uint32_t)((videoBuffer->GetWidth() * parNum) / (scale * parDen)) + 1) & ~1;
maybe std::trunc should be used instead of std::round since round(x) returns integral value that is nearest to x, which means there is possibility that x is rounded up in case of fractional part of x is greater than 0.5.  And I guess that converting a float to int as the same effect as trunc operation mathematically.

2024-05-15 21:47 UTC, yezhan10 commented on src/VideoPipe.cpp
> +		videoHeight = scaleResolutionToHeight;
sure, i was under impression that scaleResolutionDownBy is not supported anymore.

2024-05-17 06:05 UTC, bcostdolby approved these changes
lgtm

2024-05-17 06:05 UTC, bcostdolby commented on src/VideoPipe.cpp
> +		videoWidth = ((uint32_t)((videoBuffer->GetWidth() * parNum) / (scale * parDen)) + 1) & ~1;
Yes you are correct. Keep the code as it is with cast is fine.

I was thinking of it as two separate processes. 

1) Find nearest pixel with (might give something like 122.9999999 instead of 123 so should really result in 123
2) Find nearest even pixel from the pixel accurate width

But that means double rounding which causes issues as you mentioned.

2024-05-17 07:50 UTC, harryz2000 commented on src/VideoPipe.cpp
> +		videoHeight = (uint32_t)(videoBuffer->GetHeight() / scale) & ~1;
Shouldn't his also be rounded to nearest even number?
Maybe worth to create a helper function, i.e.
```
constexpr uint32_t roundToNearstEven(float value)
{
    return uint32_t(value + 1.0f) & ~1;
}
```

2024-05-17 17:58 UTC, murillo128 commented on src/VideoPipe.cpp
> +		if ((allowedDownScaling == AllowedDownScaling::SameOrLower && srcVideoHeight < scaleResolutionToHeight)
I would prefer to keep a single `if` for both `scaleResolutionDownBy` and `scaleResolutionToHeight` would be easy to cause regressions in the future if not.

2024-05-20 03:46 UTC, bcostdolby commented on src/VideoPipe.cpp
> +		if ((allowedDownScaling == AllowedDownScaling::SameOrLower && srcVideoHeight < scaleResolutionToHeight)
Are we keeping support for scaleResolutionDownBy later? I dont think we use it at all.

2024-05-20 05:44 UTC, murillo128 commented on src/VideoPipe.cpp
> +		if ((allowedDownScaling == AllowedDownScaling::SameOrLower && srcVideoHeight < scaleResolutionToHeight)
yes we are keeping it

2024-05-28 06:13 UTC, bcostdolby approved these changes
Just minor style change otherwise lgtm

2024-05-28 06:13 UTC, bcostdolby commented on src/VideoPipe.cpp
> +		if(scaleResolutionToHeight) {
By the way. Super minor but apparently our style puts opening braces on a new line. 

I have a lint script here locally somewhere I can look for and pass through. It doesnt enforce and lots of code doesnt match it but new code can.

2024-05-29 23:53 UTC, merged