DIOS-5789 Fix B-frames by adding PTS metadata used when decoders reorder frames
medooze/media-server pull request #288
Opened 2024-05-31 06:54 UTC by bcostdolby

2024-05-31 07:10 UTC, murillo128 commented on include/VideoBuffer.h
> +	void SetTSClockRate(uint32_t v) { tsClockRate = v;}
do we need a different clockrate for PTS and timestamp?

2024-05-31 07:14 UTC, bcostdolby commented on include/VideoBuffer.h
> +	void SetTSClockRate(uint32_t v) { tsClockRate = v;}
Not necessarily no. I considered removing this (partly why this is a draft). 

There are times where the clock rate changes, but that is in the packetization and so probably not relevant. I will verify there are no other cases in the code and remove next week if it isn't necessary.

2024-05-31 07:23 UTC, murillo128 requested changes

2024-05-31 07:23 UTC, murillo128 commented on include/rtp/RTPPacket.h
> +	void SetTSClockRate(uint32_t v) { tsClockRate = v;}
RTP doesn't have PTS

2024-05-31 07:23 UTC, murillo128 commented on include/video.h
> +	void SetDTS(uint64_t v) { dts = v;}
Do we need both to add both PTS and DTS  values? What would be the meaning of Timestamp then?

2024-05-31 07:23 UTC, murillo128 commented on src/VideoPipe.cpp
> +
Let's add a CopyTimingInfo to VideoBuffer as well

2024-05-31 07:50 UTC, murillo128 commented on include/VideoBuffer.h
> +	void SetPTS(uint64_t v) { pts = v;}
Not sure if for consistency we should rename `SetPTS()` to `SetPresentationTimestamp()`

2024-05-31 07:51 UTC, murillo128 commented on include/video.h
> +inline void CopyTimingInfoFromEncodedToDecoded(const VideoFrame::const_shared& videoFrame, VideoBuffer::shared& videoBuffer)
Could we try to get a better naming based on what the function does and not on where it is used?

2024-06-03 03:28 UTC, bcostdolby commented on include/rtp/RTPPacket.h
> +	void SetTSClockRate(uint32_t v) { tsClockRate = v;}
correct. this came from when I looked at this before and we had packetization between the ingest and transcoder. fixing this now.

2024-06-03 03:30 UTC, bcostdolby commented on include/VideoBuffer.h
> +	void SetTSClockRate(uint32_t v) { tsClockRate = v;}
I will probably get rid of this and just have a presentation time (no need for DTS either). I wanted to make sure it worked before cleaning it up. I knew in the past we were modifying the clock rates for packetization and started thinking about this change before that work was done.

2024-06-03 03:31 UTC, bcostdolby commented on src/VideoPipe.cpp
> +
will do

2024-06-03 03:31 UTC, bcostdolby commented on include/VideoBuffer.h
> +	void SetPTS(uint64_t v) { pts = v;}
sounds good

2024-06-03 07:12 UTC, bcostdolby commented on include/rtp/RTPPacket.h
> +	void SetTSClockRate(uint32_t v) { tsClockRate = v;}
removed

2024-06-03 07:12 UTC, bcostdolby commented on include/video.h
> +	void SetDTS(uint64_t v) { dts = v;}
Using "timestamp" and presentationTime now only where it makes sense

2024-06-03 07:13 UTC, bcostdolby commented on src/VideoPipe.cpp
> +
Was already there just updated the code to call it

2024-06-03 07:13 UTC, bcostdolby commented on include/VideoBuffer.h
> +	void SetPTS(uint64_t v) { pts = v;}
done

2024-06-03 07:14 UTC, bcostdolby commented on include/video.h
> +inline void CopyTimingInfoFromEncodedToDecoded(const VideoFrame::const_shared& videoFrame, VideoBuffer::shared& videoBuffer)
Renamed to CopyPresentedTimingInfo() as it is copying only the timing information necessary for a decoded/presented frame

2024-06-03 07:46 UTC, murillo128 commented on include/video.h
> +		presentationTime = 0;
should we reset
```
	width		= 0;
	height		= 0;
	targetBitrate	= 0;
	targetFps	= 0;
```

also for completenes?

2024-06-03 07:46 UTC, murillo128 approved these changes
lgtm

2024-06-03 08:30 UTC, harryz2000 commented on include/VideoBuffer.h
> +	void    CopyTimingInfo(const VideoBuffer::const_shared& videoBuffer)
Looks the function name could be CopyTimingInfoIfExists(...).

Otherwise, the current object's value wouldn't be changed. Is it expected?

2024-06-03 08:30 UTC, harryz2000 commented on include/video.h
> +	void SetPresentationTime(uint64_t v) { presentationTime = v;}
Can we rename the PresetntationTime to be PresentationTimestamp? Also can use use a more meaningful argument name, such as "ts"?

I always think the time is more like a EPOCH time, to similar. While Timestamp would have a special clock rate. 

I feel it would help to understand as we have quite many "time"s.

2024-06-03 08:30 UTC, harryz2000 commented on include/video.h
> +inline void CopyPresentedTimingInfo(const VideoFrame::const_shared& videoFrame, VideoBuffer::shared& videoBuffer)
It looks it is not only copying the pts, maybe rename it to `CopyFrameTimingInfo`?

2024-06-03 09:02 UTC, murillo128 commented on include/VideoBuffer.h
> +	void    CopyTimingInfo(const VideoBuffer::const_shared& videoBuffer)
right, it should reset them before setting them

2024-06-03 22:09 UTC, bcostdolby commented on include/video.h
> +inline void CopyPresentedTimingInfo(const VideoFrame::const_shared& videoFrame, VideoBuffer::shared& videoBuffer)
The issue with "CopyTimingInfo" is it doesnt indicate it is copying a PTS to a DTS in the name and sounds like it is just copying like VideoBuffer::CopyTimingInfo() that just copys 1:1 field for field.

I.e. This does:
> dts = pts
> ... copy others

The VideoBuffer::CopyTimingInfo is a real copy that does:
> dts = dts
> ... copy others

I.e. This one is changing the meaning of the timestamps at the same time as doing the copy and I dont want that to be missed in reading the code. Its been through a few different names now. Maybe we should change it to do a 1:1 copy, but then the decoders set the dts from the PTS separately?

2024-06-04 04:36 UTC, bcostdolby commented on include/video.h
> +		presentationTime = 0;
done

2024-06-04 04:36 UTC, bcostdolby commented on include/video.h
> +	void SetPresentationTime(uint64_t v) { presentationTime = v;}
done

2024-06-04 20:13 UTC, murillo128 approved these changes
lgtm

2024-06-04 20:13 UTC, merged