Report RTMP client error for event logging
medooze/media-server pull request #293
Opened 2024-06-13 23:38 UTC by harryz2000

2024-06-14 07:12 UTC, murillo128 requested changes

2024-06-14 07:12 UTC, murillo128 commented on src/rtmp/rtmpclientconnection.cpp
> +			listener->onError(this, RTMPClientConnection::ErrorCode::FailedToResolveURL);
Given that the Connect is a pure synchronous method, I would prefer to return the error code instead of firing an error event in this case.

2024-06-14 07:12 UTC, murillo128 commented on src/rtmp/rtmpclientconnection.cpp
> +			listener->onError(this, RTMPClientConnection::ErrorCode::FailedToConnectSocket);
same here

2024-06-14 07:12 UTC, murillo128 commented on src/rtmp/rtmpclientconnection.cpp
> +				if (listener) listener->onError(this, RTMPClientConnection::ErrorCode::FailedToParseData);
I don't think a parsing error should trigger an error, it could be harmless, no need to close the connection due to that.

2024-06-14 07:18 UTC, harryz2000 commented on src/rtmp/rtmpclientconnection.cpp
> +			listener->onError(this, RTMPClientConnection::ErrorCode::FailedToResolveURL);
Yes. I thought of that. In that case, we would need to change the return value to be something like 0 means success. Will look into it.

2024-06-14 07:22 UTC, harryz2000 commented on src/rtmp/rtmpclientconnection.cpp
> +				if (listener) listener->onError(this, RTMPClientConnection::ErrorCode::FailedToParseData);
Sound reasonable. The existing code actually quits the thread. If we regard it harmless, I would change it to be "continue" instead.

2024-06-14 07:43 UTC, murillo128 commented on src/rtmp/rtmpclientconnection.cpp
> +				if (listener) listener->onError(this, RTMPClientConnection::ErrorCode::FailedToParseData);
can you check what we do on the server connections?

2024-06-14 07:46 UTC, murillo128 commented on src/rtmp/rtmpclientconnection.cpp
> +			listener->onError(this, RTMPClientConnection::ErrorCode::FailedToResolveURL);
yes, maybe returning an enum could be a good idea. @mildsunrise wdyt?

2024-06-17 04:33 UTC, harryz2000 commented on src/rtmp/rtmpclientconnection.cpp
> +				if (listener) listener->onError(this, RTMPClientConnection::ErrorCode::FailedToParseData);
The server connection is like current implementation. It will "break" the loop, which means it would quit the thread in case of parse error. https://github.com/medooze/media-server/blob/c20ff2202258e03713ddb309a1da29bc5ba084e8/src/rtmp/rtmpconnection.cpp#L244

2024-06-18 06:49 UTC, murillo128 approved these changes
lgtm

2024-06-19 03:58 UTC, merged