add unit test for bframe support
medooze/media-server pull request #294
Opened 2024-06-17 23:57 UTC by yezhan10

1. add bframe unit tests for all supported decoders(h264/h265/vp8/vp9)
2. add flushing logic in h265decoder 
3. copy timing info in vp9

2024-06-20 04:22 UTC, bcostdolby requested changes

2024-06-20 04:22 UTC, bcostdolby commented on test/unit/TestBFrame.cpp
> +            for (y = 0; y < height / 2; y++)
Maybe just add a comment describing what sort of image this is generating and where this came from.

I assume it is just covering the colour space, but I dont understand it (not without reading some external docs)

Also this is obviously truncating the integers. I assume this will produce some compile warnings we should probably clean up.

2024-06-20 04:22 UTC, bcostdolby commented on test/unit/TestBFrame.cpp
> +                    frame->data[0][y * frame->linesize[0] + x] = i * 10 + 1;
Be worth adding this into a function that can be used below to provide the expected values.

2024-06-20 04:22 UTC, bcostdolby commented on test/unit/TestBFrame.cpp
> +        expectedPixelValue.push_back(10 * i + 1);
Just create a function that we can use in both places.

2024-06-24 17:40 UTC, phil-moss-dolby commented on test/unit/TestBFrame.cpp
> +TEST(TestBFrame, H264CodecBFrame)
Since we're moving in the direction of having 1:1 source file to test file structure, should we keep this TestBFrame.cpp as generic test code, but have the tests themselves running in their appropriate source files? h264 test belongs in the Testh264decoder.cpp, and that test calls runBFrameTest defining its own codec and other params. Just a file structure and organizational question

2024-07-02 03:31 UTC, bcostdolby approved these changes

2024-07-02 03:47 UTC, harryz2000 approved these changes
lgtm

2024-07-02 22:00 UTC, merged