DRAFT: Handle scte35 messages as unregistered SEI user data
medooze/media-server pull request #296
Opened 2024-06-21 00:42 UTC by amaha877

2024-06-21 01:24 UTC, murillo128 requested changes
please remove the mp4v2 from the PR

2024-06-21 01:24 UTC, murillo128 commented on include/MediaFrameListenerBridge.h
> +	void SetScteData(Buffer data);
do not use the MediaFrameListenerBridge as intermediary

2024-06-21 01:24 UTC, murillo128 commented on src/h264/H264Packetizer.h
> +	std::optional<Buffer> GetScteData();
no need for a getter

2024-06-21 01:24 UTC, murillo128 commented on src/h264/H264Packetizer.cpp
> +		/* Construct json encoded as a string
please use a binary format instead

2024-06-21 01:24 UTC, murillo128 commented on src/h264/H264Packetizer.cpp
> +		 We need to compute a unique hash for every scte payload received.
why? a unique has based on the scte data provides no info, if you need an unique id, use a counter instead

2024-06-21 01:24 UTC, murillo128 commented on src/h264/H264Packetizer.cpp
> +  			duration: 30,
duration is not used, please remove

2024-06-21 01:24 UTC, murillo128 commented on src/h264/H264Packetizer.h
> +	void SetScteData(Buffer data);
this is not really a setter, use a single method:
```suggestion
	void AppendScteData(uint64_t ts, const Buffer& data, uint8_t repeatCount);
```

2024-06-21 01:24 UTC, murillo128 commented on src/h264/H264Packetizer.cpp
> +constexpr int FrameRepeatCount = 20;
better to have this configurable from outside (see below)

2024-06-21 01:24 UTC, murillo128 commented on src/h264/H264Packetizer.cpp
> +		std::vector<uint8_t> sei;
Move the serialization to the `AppendScteData` function, so we do it only once

2024-06-21 01:24 UTC, murillo128 commented on src/h264/H264Packetizer.h
> +#include <queue>
not needed, right?

2024-06-21 03:41 UTC, harryz2000 commented on include/MediaFrameListenerBridge.h
> +	void SetScteData(Buffer data);
Yeah. Agree. This is not ideal, probably only works for prototyping. As this involves passing a data from one stream to another stream, to properly passing, we might have to find a way to pass data across different streams, then to H264Packetizer.

2024-06-24 18:44 UTC, amaha877 commented on include/MediaFrameListenerBridge.h
> +	void SetScteData(Buffer data);
Ok this was the part i wasn't too sure on how to refactor. Sounds like adding a scte listener directly to MpegTSAVCStream and MpegTSHEVCStream could be an option per harry's suggestion. I will give that a go.

2024-06-24 18:49 UTC, amaha877 commented on src/h264/H264Packetizer.cpp
> +		 We need to compute a unique hash for every scte payload received.
I assumed that was the requirement but yes a counter would do just fine in this case.

2024-06-24 18:49 UTC, amaha877 commented on src/h264/H264Packetizer.h
> +	void SetScteData(Buffer data);
ok

2024-06-24 18:58 UTC, amaha877 commented on src/h264/H264Packetizer.cpp
> +		/* Construct json encoded as a string
Agreed that transmitting raw json as a stream of bytes ins't the best. Are you using something like protobuf / some other binary encoding format elsewhere in the project?

If not, is it worth designing our own for ~100-200 bytes of data every now and then

2024-06-24 19:03 UTC, murillo128 commented on src/h264/H264Packetizer.cpp
> +		/* Construct json encoded as a string
protobuf is an overkill, 2 bytes for counter,  8 bytes for timestamp and the rest of the payload the scte message

2024-06-26 18:11 UTC, amaha877 commented on include/MediaFrameListenerBridge.h
> +	void SetScteData(Buffer data);
Now using a SCTEPublisher and SCTEReceiver interface for notifying streams directly. Thanks Harry for the suggestion

2024-06-26 18:12 UTC, amaha877 commented on src/h264/H264Packetizer.cpp
> +		/* Construct json encoded as a string
Done and discussed the same with SDK team

2024-06-26 21:53 UTC, murillo128 requested changes

2024-06-26 21:53 UTC, murillo128 commented on include/MediaFrameListenerBridge.h
> -	std::queue<PacketScheduleInfo> packets;
remove extra changes

2024-06-26 21:53 UTC, murillo128 commented on include/tools.h
> +
remove extra changes

2024-06-26 21:53 UTC, murillo128 commented on src/h264/H264Packetizer.h
> +	std::vector<uint8_t> sei;
better use Buffer
```suggestion
	Buffer sei;
```

2024-06-26 21:53 UTC, murillo128 commented on src/h264/H264Packetizer.cpp
> +	scteMessage.AppendData(data.GetData(), data.GetSize());
why are we storing the `scteMessage`?

2024-06-26 21:53 UTC, murillo128 commented on src/h264/H264Packetizer.cpp
> +	uint8_t scteBase64[scteMessage.GetSize()*2] = {0};
there is no need to convert it to base64 here, we can send the raw binary bytes to reduce the total size

2024-06-26 21:53 UTC, murillo128 commented on src/h264/H264Packetizer.cpp
> +	// [2] Payload size
we don't really need the payload size, it will be the rest of the NAL data

2024-06-26 21:53 UTC, murillo128 commented on src/h264/H264Packetizer.cpp
> +		auto seiSize = NalEscapeRbsp(seiEscaped, sizeof(seiEscaped), sei.data(), sei.size()).value();
`better scape it on the `AppendScteData()` if using buffers, this functions should be:


```
if (repeatFrameCounter>0 && !sei.IsEmpty())
{
  EmitNal(frame, BufferReader reader(sei));
  repeatFrameCounter--;
}

2024-06-26 21:53 UTC, murillo128 commented on src/h264/H264Packetizer.cpp
> +	uint8_t uuid[16] = {
```suggestion
	constexpr std::array<uint8_t,16> uuid = {
```

2024-06-26 21:53 UTC, murillo128 commented on src/h264/H264Packetizer.cpp
> +	scteMessageId++;
This could be simplified by

```
sei.Alloc(16+2+data.Size()*2)
BufferWritter(sei);
writter.Set(uuid);
writter.Set2(scteMessageId++);
auto pos = writter.Set8(timestamp);
auto size = NalEscapeRbsp(sei.GetData() + pos , writter.GetLeft(), data.GetData(), data.GetSize());
writter.Skip(size);
sei.SetSize(writter.GetLength());
```

We should add a 
```
 uint8_t GetData() { return data + pos: }
```
to the https://github.com/medooze/libdatachannels/blob/8a52932f80f7fdb569d2ff56f0481efcfe4a405f/src/internal/BufferWritter.h

so we could a NalEscape function based on writters/buffers

```
bool NalEscapeRbsp(BufferWritter& writter, const Buffer& buffer)
{
  auto size =  NalEscapeRbsp(writter.GetData() , writter.GetLeft(), data.GetData(), data.GetSize());
  writter.Skip(size);
  return size != 0;
}
```

and simplify the function even more to:
```
sei.Alloc(16+2+data.Size()*2)
BufferWritter(sei);
writter.Set(uuid);
writter.Set2(scteMessageId++);
writter.Set8(timestamp);
NalEscapeRbsp(writter, data);
sei.SetSize(writter.GetLength());
```

2024-06-27 17:27 UTC, amaha877 commented on src/h264/H264Packetizer.cpp
> +	scteMessage.AppendData(data.GetData(), data.GetSize());
Because we need to reuse the same scteMessage to provide inter frame redundancy. The appendscte method will only be called when we have an event.

2024-06-27 17:29 UTC, amaha877 commented on src/h264/H264Packetizer.cpp
> +	uint8_t scteBase64[scteMessage.GetSize()*2] = {0};
Regarding base64, that was requested by the Client team. I obliged since it was a few extra bytes and we had a routine handy

2024-06-27 17:50 UTC, amaha877 commented on src/h264/H264Packetizer.cpp
> +	scteMessage.AppendData(data.GetData(), data.GetSize());
Oh I see your point actually, we can just directly append it to the final SEI message.

2024-06-27 18:06 UTC, murillo128 commented on src/h264/H264Packetizer.cpp
> +	uint8_t scteBase64[scteMessage.GetSize()*2] = {0};
let's discuss that internally

2024-06-27 18:07 UTC, murillo128 commented on src/h264/H264Packetizer.cpp
> +	uint8_t scteBase64[scteMessage.GetSize()*2] = {0};
re, payloadSize, note that it is an input tobthe serialization function but it is not serialized

2024-06-27 18:12 UTC, murillo128 commented on src/h264/H264Packetizer.cpp
> +	scteMessageId++;
my bad, we need to scape the whole mal unit not just the scte data, the function would be even easier

Buffer unscaped(16+2+data.Size())
BufferWritter(unscaped);
writter.Set(uuid);
writter.Set2(scteMessageId++);
writter.Set8(timestamp);
writter.Set(data);
sei.SetSize(writter.GetLength());


and then scape it later as you already have

2024-06-27 20:41 UTC, phil-moss-dolby commented on src/h264/H264Packetizer.cpp
> +	uint8_t scteBase64[scteMessage.GetSize()*2] = {0};
Ticket created to finalize payload format (let's make sure client team is involved in this discussion to prevent the back and forth, every time we update they have to as well): https://jira.dolby.net/jira/browse/DIOS-6124 

In the meantime, let's address the functional comments and get this merged to unblock the client team as they would like to start demoing next week. Unless if we feel we can agree on something before Monday, I don't believe the final formatting should block this functionality while @murillo128 is on vacation

2024-07-03 00:06 UTC, phil-moss-dolby commented
Merging to unblock Bally's testing and demos in stage, quick follow up: https://jira.dolby.net/jira/browse/DIOS-6124. If there are side effects during QA testing this will be removed from the build

2024-07-03 00:35 UTC, merged