Improve the locking for frame delay cacluation
medooze/media-server pull request #305
Opened 2024-07-04 02:17 UTC by harryz2000

2024-07-04 07:19 UTC, murillo128 commented
I think it would be easier to add a TimeService to the coordinator and call the OnFrame and SetMaxDelayMs on an Async call. The MediaFrameBridgeListener call is already thread safe.

2024-07-04 09:08 UTC, harryz2000 commented
> I think it would be easier to add a TimeService to the coordinator and call the OnFrame and SetMaxDelayMs on an Async call. The MediaFrameBridgeListener call is already thread safe.

Yes. That would solve the thread lock issue. But to me, it seems not ideal as the calculated delay may not be used for current frame. For cases such as receive a batch of audio frames, they may still use a same delay, which might not be smooth.

Although, in practice, it might not be a issue. I am trying to see if it could be solved by another way. Got some progress, will need spend a bit more time to ensure it works.

2024-07-04 11:39 UTC, harryz2000 commented
This should be a draft full solution for this issue. There is still a test to fix. But it should work. 

It calculates the delay in synchronously without lock. On the other hand it reduces latency asynchronously if all frames come early. Now the OnFrame is thread safe.

Yes. It has been a bit harder to implement this. But imho it suits better for our expectation.

2024-07-05 07:26 UTC, harryz2000 commented
@murillo128 Now all unit tests have passed. I did some manual tests well. It works well to me, so I think it is ready for formal review. Personally, I would prefer this solution. It actually becomes cleaner now: One part is for delay calculation, which is lock-free sync operations. Another part for latency reduction, which uses async calls.

The test is using a TestTimeService which does sync calls for Async(), therefore most of the tests passed. The only test failed and has been fixed is the latency reduction may be delayed by one frame, as we are not reduce the delay immediately. However it shouldn't matter.

2024-08-20 07:19 UTC, murillo128 requested changes

2024-08-22 08:46 UTC, murillo128 commented on include/FrameDelayCalculator.h
> +	union alignas (16) Reference
@harryz2000 ptal

2024-08-28 11:29 UTC, murillo128 commented on include/FrameDelayCalculator.h
> +	union alignas (16) Reference
@harryz2000 ping?

2024-08-29 00:38 UTC, harryz2000 commented on include/FrameDelayCalculator.h
> +	union alignas (16) Reference
If we use  a class only for the fields, it would be like:
```
struct Reference
{
		__uint128_t value;
		struct
		{
			int64_t refTime;
			uint64_t refTimestamp;
		} content;
}
```

Then we still need to unpack/pack the value from/to the content. Using a uninon is convenient as it is automatically converted and no need extra memory.

I would create an up class to wrap the function, which might make things simpler.

2024-08-29 01:05 UTC, harryz2000 commented on include/FrameDelayCalculator.h
> +	union alignas (16) Reference
Using union is convenient for pack/unpack the 128bit data. I would create a class to wrap the write/read calls.

2024-08-29 01:11 UTC, harryz2000 commented on src/FrameDelayCalculator.cpp
> +void SyncWriteUint128(__uint128_t *dst, __uint128_t value)
sure

2024-08-29 03:35 UTC, harryz2000 commented on include/FrameDelayCalculator.h
> +	union alignas (16) Reference
Done

2024-09-04 07:52 UTC, murillo128 approved these changes
lgtm

2024-09-04 07:52 UTC, murillo128 commented on include/FrameDelayCalculator.h
> +		std::pair<int64_t, uint64_t> Get();
could we use std::chrono::milliseconds on the getter/setters to remove the coversions on the main code?

2024-09-04 07:52 UTC, murillo128 commented on test/unit/TestFrameDelayCalculator.cpp
> +	int cnt = 0;
is this variable used at all?

2024-09-04 11:51 UTC, murillo128 commented on test/unit/TestFrameDelayCalculator.cpp
> +	int cnt = 0;
```suggestion
```

2024-09-04 11:53 UTC, murillo128 commented on include/FrameDelayCalculator.h
> +		void Set(int64_t refTime, uint64_t refTimestamp);
```suggestion
		void Set(std::chrono::milliseconds refTme, uint64_t refTimestamp);
```

2024-09-04 11:53 UTC, murillo128 commented on include/FrameDelayCalculator.h
> +		std::pair<int64_t, uint64_t> Get();
```suggestion
		std::pair<std::chrono::milliseconds, uint64_t> Get();
```

2024-09-04 11:58 UTC, murillo128 commented on src/FrameDelayCalculator.cpp
> +		reference.Set(now.count(), unifiedTs);
```suggestion
		reference.Set(now, unifiedTs);
```

2024-09-04 11:58 UTC, murillo128 commented on src/FrameDelayCalculator.cpp
> +				std::chrono::milliseconds(refTime), refTimestamp);
```suggestion
				refTime, refTimestamp);
```

2024-09-04 11:58 UTC, murillo128 commented on src/FrameDelayCalculator.cpp
> +		reference.Set(0, refTimestamp);
```suggestion
		reference.Set(0ms, refTimestamp);
```

2024-09-04 11:58 UTC, murillo128 commented on src/FrameDelayCalculator.cpp
> +		refTime = now.count();
```suggestion
		refTime = now;
```

2024-09-04 11:58 UTC, murillo128 commented on src/FrameDelayCalculator.cpp
> +		reference.Set(now.count(), unifiedTs);
```suggestion
		reference.Set(now, unifiedTs);
```

2024-09-04 11:58 UTC, murillo128 commented on src/FrameDelayCalculator.cpp
> +		reference.Set(now.count(), unifiedTs);
```suggestion
		reference.Set(now, unifiedTs);
```

2024-09-04 11:58 UTC, murillo128 commented on src/FrameDelayCalculator.cpp
> +				auto frameLateMs = GetFrameArrivalDelayMs(time, timestamp, std::chrono::milliseconds(refTime), refTimestamp);
```suggestion
				auto frameLateMs = GetFrameArrivalDelayMs(time, timestamp, refTime, refTimestamp);
```

2024-09-04 11:58 UTC, murillo128 commented on src/FrameDelayCalculator.cpp
> +	return { currentRef.content.refTime, currentRef.content.refTimestamp };
```suggestion
	return { std::chrono::millisecondscurrentRef.content.refTime), currentRef.content.refTimestamp };
```

2024-09-04 11:58 UTC, murillo128 commented on src/FrameDelayCalculator.cpp
> +std::pair<int64_t, uint64_t> FrameDelayCalculator::Reference::Get()
```suggestion
std::pair<std::chrono::milliseconds, uint64_t> FrameDelayCalculator::Reference::Get()
```

2024-09-04 11:58 UTC, murillo128 commented on src/FrameDelayCalculator.cpp
> +void FrameDelayCalculator::Reference::Set(int64_t refTime, uint64_t refTimestamp)
```suggestion
void FrameDelayCalculator::Reference::Set(std::chrono::milliseconds refTime, uint64_t refTimestamp)
```

2024-09-04 11:58 UTC, murillo128 commented on src/FrameDelayCalculator.cpp
> +	newRef.content = {refTime, refTimestamp};
```suggestion
	newRef.content = {refTime.count(), refTimestamp};
```

2024-09-04 11:58 UTC, murillo128 commented on src/FrameDelayCalculator.cpp
> +	ReferenceField newRef;
Would this work?
```suggestion
	ReferenceField newRef = {{{refTime.count(), refTimestamp}}};
```

2024-09-04 23:55 UTC, harryz2000 commented on include/FrameDelayCalculator.h
> +		std::pair<int64_t, uint64_t> Get();
Yes. We can

2024-09-05 00:46 UTC, harryz2000 commented on src/FrameDelayCalculator.cpp
> +	ReferenceField newRef;
Yes. We can do similar thing as that. But need the order of the fields changed. Done.

2024-09-05 01:32 UTC, harryz2000 commented
@murillo128 Please have a look at this commit: https://github.com/medooze/media-server/pull/305/commits/4ec2a6ea509dabc73bd52ed9e7f82e6c5885bb19
I tweaked the code as currently the FrameArriveInfo would only be changed asynchronously. Also added "State" to clarify the case.

2024-09-05 02:57 UTC, yezhan10 commented on include/FrameDelayCalculator.h
> +class FrameDelayCalculator : public std::enable_shared_from_this<FrameDelayCalculator>
maybe irrelevant, what's the benefit of inheriting enabled_shared_from_this? i dont see shared_from_this or weak_from_this being used in framedelaycalculator.

2024-09-06 08:03 UTC, harryz2000 commented on include/FrameDelayCalculator.h
> +class FrameDelayCalculator : public std::enable_shared_from_this<FrameDelayCalculator>
We do use the weak_from_this() in the implement file. See line 91.
`timeService.Async([selfWeak = weak_from_this(), early, now, unifiedTs, refTime, refTimestamp,`

2024-09-06 08:05 UTC, merged