Add timestamp checking
medooze/media-server pull request #316
Opened 2024-08-13 06:32 UTC by harryz2000

2024-08-15 06:37 UTC, bcostdolby reviewed
Should wait until after 2.19.0 to merge IMO

2024-08-15 06:37 UTC, bcostdolby commented on src/MediaFrameListenerBridge.cpp
> +				Error("Invalid timestamp. status: %d, info: %s, corrected: %llu\n", int(status), frame->TimeInfoToString().c_str(), rts);
Minor: Can we log the status as a enum string to make the logs easier to read?

2024-08-15 06:37 UTC, bcostdolby commented on include/MediaFrameListenerBridge.h
> +	MediaFrameListenerBridge(TimeService& timeService, DWORD ssrc, bool smooth = false, bool checkTimestamp = false);
I assume this is to prevent it being used for things like transcode layers? Usage code isnt in this PR

2024-08-15 06:37 UTC, bcostdolby commented
Please update the PR title to use the conventional commits format

2024-08-15 06:47 UTC, harryz2000 commented on src/MediaFrameListenerBridge.cpp
> +				Error("Invalid timestamp. status: %d, info: %s, corrected: %llu\n", int(status), frame->TimeInfoToString().c_str(), rts);
Will do.

2024-08-15 06:48 UTC, harryz2000 commented on include/MediaFrameListenerBridge.h
> +	MediaFrameListenerBridge(TimeService& timeService, DWORD ssrc, bool smooth = false, bool checkTimestamp = false);
Yes. It is to make it disabled by default

2024-08-15 06:50 UTC, harryz2000 commented
> Please update the PR title to use the conventional commits format

Have we got one agreed format? :)

2024-08-20 07:00 UTC, murillo128 requested changes

2024-08-21 03:52 UTC, harryz2000 commented on src/MediaFrameListenerBridge.cpp
> +				Error("Invalid timestamp. status: %d, info: %s, corrected: %llu offset: %lld \n",
The issue here is we don't enable warning level logging. If we change to warning, we would lose the information that is very important for debugging.

2024-08-21 04:08 UTC, harryz2000 commented on src/MediaFrameListenerBridge.cpp
> +				auto pts = rts + vframe->GetPresentationTimestamp() - vframe->GetTimestamp();
The rationale is the pts is not far from ts and pts should be always >0. But yes this calculation has issues. I will add another checker for it.

2024-08-22 08:00 UTC, murillo128 commented on src/rtp/RTPIncomingMediaStreamDepacketizer.cpp
> +		auto [status, rts] = tsChecker.Check(frame->GetTime(), frame->GetTimeStamp(), frame->GetClockRate());
not sure if i want to put this code here, as it only would change the timestamps for the media frames, but not the timestamps for the rtp packets

2024-08-22 08:04 UTC, harryz2000 commented on src/rtp/RTPIncomingMediaStreamDepacketizer.cpp
> +		auto [status, rts] = tsChecker.Check(frame->GetTime(), frame->GetTimeStamp(), frame->GetClockRate());
That is right. We don't see a lot of timestamp issues for WebRTC except the rare random invalid timestamps. The check is critical for recordings, A/V sync, etc. But might not be that critical for WebRTC.

But we could change RTP packet timestamp as well.

2024-08-29 00:00 UTC, merged