Change RTMPClientConnection to use EventLoop
medooze/media-server pull request #317
Opened 2024-08-16 00:19 UTC by harryz2000

2024-08-19 15:33 UTC, mildsunrise reviewed
I still need to take a deeper look but lgtm so far. always happy to move more of our code using the legacy `createPriorityThread` API into `EventLoop`

2024-08-20 07:19 UTC, murillo128 reviewed
lgtm, wondering if we can reuse more of the `EventLoop` functionality here though

2024-08-20 07:19 UTC, murillo128 commented on src/rtmp/rtmpclientconnection.cpp
> +	auto threadHandle = GetThread().native_handle();
can't we just call `EventLoop::Signal()` instead?

2024-08-21 04:40 UTC, harryz2000 commented on src/rtmp/rtmpclientconnection.cpp
> +	auto threadHandle = GetThread().native_handle();
yeah. That works too.

2024-08-22 07:42 UTC, murillo128 requested changes

2024-08-22 07:42 UTC, murillo128 commented on src/rtmp/rtmpclientconnection.cpp
> +	auto threadHandle = GetThread().native_handle();
please change it then

2024-08-22 07:48 UTC, harryz2000 commented on src/rtmp/rtmpclientconnection.cpp
> +	auto threadHandle = GetThread().native_handle();
Yep. Haven't been able to come to this PR yet. Trying to resolve the rtmps first. This PR would be low priority as it would be not necessary but a good to have change as the timeservice here may not be used.

2024-08-23 01:15 UTC, harryz2000 commented on src/rtmp/rtmpclientconnection.cpp
> +	auto threadHandle = GetThread().native_handle();
Done

2024-08-23 01:20 UTC, harryz2000 commented
> lgtm, wondering if we can reuse more of the `EventLoop` functionality here though

I tried to reuse some members of EventLoop. But I feel it makes things a bit messy. I would prefer to keep the current change. 

Maybe on another PR, we could optimise the EventLoop a bit to make it easy to be extended. Such as if we could reuse the Run() function. If we could split the network functionality from a Basic EventLoop, i.e. Created a class such as NetEventLoop.  Those idea would need a further review of the code and a larger change.

2024-08-28 11:27 UTC, murillo128 approved these changes
lgtm

2024-08-29 00:12 UTC, merged