improve audio encoder timestamp
medooze/media-server pull request #335
Opened 2024-09-03 22:39 UTC by yezhan10

Instead of honoring timestamp from decoder, audio encoder always start from 0 and add frame length. This would be problematic in case of lost packets or pts wraparound. This change is to allow audio encoder follow timestamps from audio frame.

2024-09-04 07:40 UTC, murillo128 commented on CMakeLists.txt
> +    # ${SOURCES_MP3}
please revert

2024-09-04 07:40 UTC, murillo128 commented on CMakeLists.txt
> +    ${CMAKE_CURRENT_LIST_DIR}/src/AudioDecoderWorker.cpp
🥳

2024-09-04 07:40 UTC, murillo128 commented on include/AudioPipe.h
> +	virtual DWORD RecBuffer(DWORD frameSize, const AudioBuffer::shared& audioBuffer);
Let's return it instead
```suggestion
	virtual  AudioBuffer::shared RecBuffer(DWORD frameSize);
```

2024-09-05 03:23 UTC, yezhan10 commented on include/AudioPipe.h
> +	virtual int PlayBuffer(SWORD *buffer,DWORD size, QWORD pts, BYTE vadLevel = -1);
My initial thought is to push audio buffer to a queue. I discarded this since decoded audio frame size and required audio frame size may differ, for aac, each playbuffer we write 1024*numChannels worth of samples, but opus requires totally different frame size (960, 1920 etc) to encode. so the logic of consuming the pcm data might be complicated, and i still need a small fifo buffer serves as a cache in case requested number of samples from encoder is less than number of sampling in audio buffer.

2024-09-05 03:37 UTC, yezhan10 commented on include/AudioPipe.h
> +	std::queue<std::pair<QWORD, QWORD>> audioPts;
i think it might be more complicated if we have a queue of audio buffers? I will give more thoughts on this..

2024-09-05 04:33 UTC, bcostdolby commented on src/AudioPipe.cpp
> +		if(encoderPTS + frameSize <= ref + decoderFrameSize)
Please rename everything to be consistent. Its difficult to read as every time i find a new variable I need to trace back how it is used to know what it is.

I think (are these meanings correct?):
* encoderNextPTS = encoderPTS
* encoderCurrentPTS = ts
* encodeFrameSize = frameSize 
* decoderNextPTS = ref
* decoderFrameSize = decoderFrameSize
* decoderFirst = first

2024-09-05 04:33 UTC, bcostdolby commented on src/AudioPipe.cpp
> +			// since timestamps are considered as continuous
But didnt we just maybe drop multiple items from the audioPts queue above?

2024-09-05 04:33 UTC, bcostdolby commented on src/AudioPipe.cpp
> +		if(encoderPTS + frameSize <= ref + decoderFrameSize)
I may have been very wrong in the above...

It looks like encoderPTS at the start of this function call holds  the PTS expected to be given to the first sample in the next block we pull from the fifo?

2024-09-05 04:33 UTC, bcostdolby commented on src/AudioPipe.cpp
> +				if(encoderPTS + frameSize <= ref + decoderFrameSize)
Think I need to ask about this as well

2024-09-06 07:45 UTC, murillo128 commented
In order to be able to progress this PR, can we split it in two PRs? 

The first one about method changes to use the AudioBuffer and the second one to fix the timestamp calculation inside the AudioPipe?

2024-09-09 22:51 UTC, yezhan10 commented
> In order to be able to progress this PR, can we split it in two PRs?
> 
> The first one about method changes to use the AudioBuffer and the second one to fix the timestamp calculation inside the AudioPipe?

@murillo128 @bcostdolby I have updated the implementation to use a queue of audio buffers in audio pipe, and also added timestamp calculation for audio buffer based on decoder pts.  if we all like this approach better, i will clean up the code a bit in my next commit. This version still has `Encode(const AudioBuffer::const_shared& audioBuffer, BYTE* out, int outLen)`, I will update this to return an encoded frame in next PR most likely. Also, maybe we can use audiobuffer pool as an improvement in the next PR as well to avoid frequent audio buffer creation.

2024-09-10 01:26 UTC, bcostdolby commented on include/AudioBuffer.h
> +		if(numSamples*numChannels > pcmBuffer.capacity())
Probably should be looking at size not capacity unless we are resizing the buffer as we go.

Also the each channel is doing a std::min with 2 and this does not so will miss the check

2024-09-10 01:26 UTC, bcostdolby commented on include/AudioBuffer.h
> +		if(!pcmData || !*pcmData)
Possibly need to check more than just pcmData[0] != nullptr but also for all other possible channels. 

Overall this API isnt very safe might be worth rethinking. We have num samples passed in but not num channels and it is implicitly expected to be equal to min(numChannels, 2) which is non obvious

2024-09-10 01:26 UTC, bcostdolby commented on src/AudioPipe.cpp
> +		QWORD scaledDecoderPTS = std::round<QWORD>((decoderPTS-decoderPTSOffset) * (recordRate / (double)playRate)) + decoderPTSOffset;
Tomorrow when we chat again, might need to understand why we need to scale the PTS based on the resampling. I.e. For example if the ingest clock rate as from SRT is say 1000Hz and the PTS is 5000 (so 5 sec in roughly) and the incoming audio sample rate is say 16KHz (which is different from the PTS clock).

Lets say we need to resample to 32KHz we still would push PTS meta-data for the first sample in the block with a PTS = 5000 and a PTS Clock = 1000Hz as although there are now twice as many samples, they are still for the same point in time according to the PTS clock.

I dont see us changing the PTS clock in the code here (dont think we need to, but to work with this rescaling of PTS I assume we would also need to rescale the PTS clock from 1000Hz to 2000Hz).

2024-09-10 01:26 UTC, bcostdolby commented on src/AudioPipe.cpp
> +	audioBuffer->SetClockRate(recordRate);
Ahh related to comment above. I see we are changing the PTS clock here. I dont think we need to do this right?

I.e. The sample rate clock and the PTS clock are two different things arent they?

2024-09-10 01:26 UTC, bcostdolby commented on src/AudioPipe.cpp
> +		rateBlockBuffer.pop(audioBuffer->GetAudioBufferData(requiredNumSamples), requiredNumSamples);
Dont need separate if statement block for this. Just take min(requiredNumSamples,cachedSamples) from cache (might be 0 or more up to needed size)

I.e. I think most of these if/else blocks can be flattened into a single loop.

2024-09-11 23:37 UTC, yezhan10 commented on include/AudioBuffer.h
> +		pcmBuffer.resize(numSamples*numChannels);
i removed this function since it's unused

2024-09-11 23:41 UTC, yezhan10 commented on include/AudioBuffer.h
> +		if(!pcmData || !*pcmData)
the min(numChannels,2) is from the old code, i guess this indicates that our system does not support multichannel audio.  i have removed the min(numChannels,2) and added check for each channel's data pointer

2024-09-12 22:13 UTC, murillo128 requested changes
looking better, still some changes I would like to make

2024-09-12 22:13 UTC, murillo128 commented on include/AudioBuffer.h
> +	bool AddPCM(SWORD val, int pos)
I am not sure if I prefer having a getter for the `std::vector` or overloading the  `[]` instead. 

At most
```suggestion
	bool SetSample(size_t pos, SWORD sample) 
```

2024-09-12 22:13 UTC, murillo128 commented on include/AudioBuffer.h
> +	SWORD* data;
I don't think we should keep reader state inside this class

2024-09-12 22:13 UTC, murillo128 commented on include/AudioPipe.h
> +	QWORD encoderPTS = 0;
let's remove for now

2024-09-12 22:13 UTC, murillo128 commented on src/opus/OpusEncoder.h
> +	virtual AudioFrame* Encode(const AudioBuffer::const_shared& audioBuffer);
can we return a AudioFrame::shared better? We could add an <ObjectPool> to the  encoders for increasing performance if needed.

2024-09-12 22:13 UTC, murillo128 commented on include/audio.h
> +	virtual AudioFrame* Encode(const AudioBuffer::const_shared& audioBuffer) = 0;
can we use a shared pointer better?### 
```suggestion
	virtual AudioFrame::shared Encode(const AudioBuffer::const_shared& audioBuffer) = 0;

```

2024-09-13 01:49 UTC, yezhan10 commented on include/AudioBuffer.h
> +	SWORD* ConsumeData(int numSamples)
this function is used in gsmcodec.cpp gsm_decode() line 92/96.

2024-09-13 01:53 UTC, yezhan10 commented on include/AudioBuffer.h
> +	bool AddPCM(SWORD val, int pos)
I chose to use getter function and i would rename it to SetSampleAt() to have more obvious distinction between SetSamples()

2024-09-13 01:54 UTC, yezhan10 commented on include/AudioBuffer.h
> +	SWORD* data;
the reader position is needed in ConsumeSamples() function which is used in gsmcodec.cpp. I will leave it for now.

2024-09-13 06:10 UTC, murillo128 commented on include/AudioBuffer.h
> +	SWORD* ConsumeData(int numSamples)
I don't like keeping a read state inside the `AudioBuffer`. The same `AudioBuffer` could be passed to multiple `AudioEncoders` so it feels weird do modify the state just when reading samples.

2024-09-13 06:15 UTC, murillo128 requested changes

2024-09-13 06:15 UTC, murillo128 commented on src/gsm/gsmcodec.cpp
> +		if (gsm_decode(g,(gsm_byte *)in,(gsm_signal *)audioBuffer->ConsumeSamples(160))<0)
```suggestion
		if (gsm_decode(g,(gsm_byte *)in,(gsm_signal *)audioBuffer->GetData(160))<0)
```

2024-09-13 06:15 UTC, murillo128 commented on src/gsm/gsmcodec.cpp
> +		if (gsm_decode(g,(gsm_byte *)&in[33],(gsm_signal *)audioBuffer->ConsumeSamples(160))<0)
```suggestion
		if (gsm_decode(g,(gsm_byte *)&in[33],(gsm_signal *)(audioBuffer->GetData()+160))<0)
```

2024-09-13 06:15 UTC, murillo128 commented on src/gsm/gsmcodec.cpp
> +	audioFrameInfo.first = in;
why don't acually decode here and have a FIFO of the produced `AudioBuffers` that are consumed in the `GetDecodedAudioFrame()`?

As you are not keeping the `audioFrame` shared pointer, `in` pointer can be invalid when `GetDecodedAudioFrame()` is called

2024-09-16 18:21 UTC, yezhan10 commented on src/gsm/gsmcodec.cpp
> +	audioFrameInfo.first = in;
i agree that decode here instead of in GetDecodeAudioFrame() is more safe. Do we need a queue of audiobuffers stored for these codecs(g711 etc)? Looks like audioFrame only contains one decoded frame for these codecs.

2024-09-17 20:13 UTC, murillo128 approved these changes
lgtm

2024-09-17 20:13 UTC, murillo128 commented on src/g711/pcmacodec.cpp
> +	if(!audioBufferQueue.empty())
not big deal, but I preffer to fail early

```
if(audioBufferQueue.empty())
  return {};
auto audioBuffer = audioBufferQueue.front();
audioBufferQueue.pop();
return audioBuffer;
}

```

2024-09-18 09:24 UTC, merged