refactor:calculate encoder pts based on decoder pts
medooze/media-server pull request #348
Opened 2024-09-23 18:04 UTC by yezhan10

2024-09-24 07:35 UTC, murillo128 requested changes

2024-09-24 07:35 UTC, murillo128 commented on include/AudioBuffer.h
> +	uint16_t SetSamples(int16_t* in, uint16_t numSamples, size_t offset=0, bool allowResize=false)
not sure if I like the flag, is there any case in which do we do not want to allow resize?

if we want to allow resizing only for certain cases, wouldn't it be better to have an explicit `Resize()` method instead?

2024-09-24 07:35 UTC, murillo128 commented on include/AudioBuffer.h
> +		else if (!allowResize && pcmBuffer.size() < offset+totalSamples)
simplify the if/else please

2024-09-24 07:35 UTC, murillo128 commented on include/AudioPipe.h
> +	QWORD decoderFrameSize = 0;
rename, there ir no `decoder` in this context so not sure what is referring too just by looking at the variable name

2024-09-24 07:35 UTC, murillo128 commented on src/AudioPipe.cpp
> +	if (decoderPTSOffset == std::numeric_limits<QWORD>::max())
better to use `std::optional` instead

2024-09-24 07:35 UTC, murillo128 commented on src/AudioPipe.cpp
> +		auto decoderPTS = audioBuffer->GetTimestamp();
can we make `transrater` use `AudioBuffer` for in/out and do the pts calculus inside of it?

2024-09-24 07:35 UTC, murillo128 commented on src/AudioPipe.cpp
> +		needSamples -= frontAudioBuffer->GetNumSamples();
what happnes if `neededSampes<frontAudioBuffer->GetNumSamples()` wouldn't we be dropping samples?

2024-09-24 07:35 UTC, murillo128 commented on src/AudioPipe.cpp
> +		auto currDecoderPTS = frontAudioBuffer->GetTimestamp();
imho it is simpler/safer to keep the timestamp of the first AudioBuffer as reference and not the latest one, it will simplify calculus

2024-09-24 19:49 UTC, yezhan10 commented on include/AudioBuffer.h
> +	uint16_t SetSamples(int16_t* in, uint16_t numSamples, size_t offset=0, bool allowResize=false)
the idea is that the only allow resize in case of resampling. This SetSamples() is used in recBuffer() function as well where resize is disallowed.

2024-09-24 20:02 UTC, murillo128 commented on include/AudioBuffer.h
> +	uint16_t SetSamples(int16_t* in, uint16_t numSamples, size_t offset=0, bool allowResize=false)
but resampling should produce a different audio buffer not reuse current one.  There should be possible to have multiple consumers for the same AudioBuffer, so the only ones allowed to change the AudioBiffers are the producers

2024-09-24 20:08 UTC, yezhan10 commented on src/AudioPipe.cpp
> +	AudioBuffer::const_shared frontAudioBuffer;
Since the audioBuffer created for encoder may include fractional number of audio buffer produced by decoders, I used rateBlockBuffer to store the leftover. For example, if encoder audio buffer requires 2.3 decoder audio buffers to make up the encoder frame size, this code block would pop 3 decoder audio buffers, and write the leftover( = 0.7*audio buffer samples) to rateBlockBuffer. To achieve this, it requires to read whatever in rateBlockBuffer first, if still need more samples, and then pop the audioBufferQueue based on number of samples still required from audio buffer queue.

2024-09-24 20:09 UTC, yezhan10 commented on src/AudioPipe.cpp
> +		needSamples -= frontAudioBuffer->GetNumSamples();
samples are not dropped, the leftover are stored in rateBlockBuffer.

2024-09-24 20:16 UTC, yezhan10 commented on src/AudioPipe.cpp
> +		auto currDecoderPTS = frontAudioBuffer->GetTimestamp();
um i think the encoder PTS uses the first as reference: 
`auto encoderPTS = bufferedSamples ? rateBlockBufferPTS : queue.front()->GetTimestamp();`
if we have any samples in rateBlockBuffer, encoderPTS= rateBlockBufferPTS, otherwise, it equals to the first audio buffer. The pts related logic inside this while loop is mostly to infer rateBlockBufferPTS.

2024-09-24 20:20 UTC, murillo128 commented on src/AudioPipe.cpp
> +		auto currDecoderPTS = frontAudioBuffer->GetTimestamp();
why does it needs to be fine inside the loop? we just need to update it on the latest buffer, rigth?

2024-09-24 20:20 UTC, yezhan10 commented on include/AudioBuffer.h
> +	uint16_t SetSamples(int16_t* in, uint16_t numSamples, size_t offset=0, bool allowResize=false)
maybe I can update the transrater to produce a new audio buffer instead of resizing?

2024-09-24 20:28 UTC, yezhan10 commented on src/AudioPipe.cpp
> +		auto currDecoderPTS = frontAudioBuffer->GetTimestamp();
yeah most of the cases, rateBlockBufferPTS is updated based on the last buffer. And only in case of ts wraparound between rateBlockBuffer and first audio buffer, encoderPTS is updated inside.

2024-10-01 21:21 UTC, murillo128 reviewed
lgtm so far, need to review the `RecBuffer()` though

2024-10-01 21:25 UTC, murillo128 commented on src/AudioPipe.cpp
> +		else if (currPlayPTS > prevPTS + 2*numSamples)
should we break in case of discontinuity?

2024-10-02 00:16 UTC, yezhan10 commented on include/AudioBufferPool.h
> +	AudioBuffer::shared Acquire()
I renamed to acquire since it seems to be more accurate. I will rename VideoBufferPool to use acquire instead.

2024-10-02 00:40 UTC, yezhan10 commented on src/AudioTransrater.cpp
> +	audioBufferPool.SetSize(bufferSize, audioBuffer->GetNumChannels());
according to the overall logic, num of channels in AudioDecoderWorker == number of channels in AudioPipe == num of channels in AudioTransrater. Unless there is channel count change happen in the middle of an audio stream, i would expect that audioBuffer->GetNumChannels always == numChannels in AudioTransrater. Probably put an assert? The audio would be corrupted if those two are not equal anyways unless we reinitialize the transrater with updated channel count.

2024-10-02 07:25 UTC, murillo128 requested changes

2024-10-02 07:25 UTC, murillo128 commented on src/AudioPipe.cpp
> +	auto bufferedSamples = rateBlockBuffer.length() / numChannels;
remove

2024-10-02 07:25 UTC, murillo128 commented on src/AudioPipe.cpp
> +	rateBlockBuffer.pop(buffer, readSamples*numChannels);
too many variables here, makes it hard to follow and easy to make mistakes
```suggestion
	rateBlockBuffer.pop(audioBuffer->GetData(), readSamples);
```

2024-10-02 07:25 UTC, murillo128 commented on src/AudioPipe.cpp
> +	auto readSamples = std::min(bufferedSamples, frameSize);
```suggestion
	auto readSamples = std::min(rateBlockBuffer.length(), requiredNumSamples);
```

2024-10-02 07:25 UTC, murillo128 commented on src/AudioPipe.cpp
> +	int needSamples = frameSize - readSamples;
reuse `requiredSamples`
```suggestion
	requiredSamples -= readSamples;
```

2024-10-02 07:25 UTC, murillo128 commented on src/AudioPipe.cpp
> +	AudioBuffer::const_shared frontAudioBuffer;
the code bellow is really hard to understand, too many variables and also mixes pts and frame read/pop, would it be possible to simplify it a bit further?

2024-10-02 17:45 UTC, yezhan10 commented on src/AudioPipe.cpp
> +	auto bufferedSamples = rateBlockBuffer.length() / numChannels;
remove the bufferedSamples variable? use rateBlockBuffer.length() / numChannels directly?

2024-10-02 17:48 UTC, yezhan10 commented on src/AudioPipe.cpp
> +	auto bufferedSamples = rateBlockBuffer.length() / numChannels;
got it, have to continue to finish reading all comments.

2024-10-03 01:44 UTC, yezhan10 commented on src/AudioPipe.cpp
> +	AudioBuffer::const_shared frontAudioBuffer;
tried to remove unnecessary variables definitions. Sorry that i can not simplify the logic further

2024-10-04 07:32 UTC, murillo128 reviewed
almost lgtm

2024-10-04 07:32 UTC, murillo128 commented on src/AudioPipe.cpp
> +		if (frontAudioBuffer->GetTimestamp() > 2 * samples + prevPTS)
shouldn't be the timestamp threshold for detecting a discontinuity be a static constant and not depending on the samples?

2024-10-08 11:46 UTC, murillo128 commented on src/AudioPipe.cpp
> +		if (frontAudioBuffer->GetTimestamp() > 2 * samples + prevPTS)
yes, I meant a timestamp threshold converted to the num samples based on the output clock rate.

2024-10-08 11:51 UTC, murillo128 commented on src/AudioPipe.cpp
> +		if (frontAudioBuffer->GetTimestamp() > 2 * samples + prevPTS)
what I meant is that we are detecting the disconituity based on the leftovers of the `rateBlockBuffer` which is variable

2024-10-08 11:51 UTC, murillo128 commented on src/AudioTransrater.cpp
> +	audioBufferPool.SetSize(bufferSize, audioBuffer->GetNumChannels());
`AudioDecoderWorker` may not be the only class using the transrater, we can't just ensure the behaviour of a class based on the use done from outside of it.

2024-10-08 11:51 UTC, murillo128 commented on src/AudioPipe.cpp
> +		audioBuffer->SetSamples(const_cast<int16_t*>(frontAudioBuffer->GetData()), neededSamples ,readedSamples);
isn't it weird that `GetNumSamples` return the `samples` count  but `SetSamples` uses `samples * channel` ?

2024-10-08 20:36 UTC, yezhan10 commented on src/AudioPipe.cpp
> +		audioBuffer->SetSamples(const_cast<int16_t*>(frontAudioBuffer->GetData()), neededSamples ,readedSamples);
i will update the code so that GetNumSamples() return samples*channel.

2024-10-10 07:01 UTC, murillo128 approved these changes
lgtm

2024-10-10 07:01 UTC, merged