DIOS-7112 Further refactor EventLoop to enable it to be used for different poll mechanism
medooze/media-server pull request #349
Opened 2024-09-24 06:32 UTC by harryz2000

2024-09-24 09:21 UTC, murillo128 commented on include/EventLoop.h
> +	bool AddFd(FileDescriptor fd) override;
we already have a file descriptor object , could we try to reuse it?

2024-09-24 09:21 UTC, murillo128 commented on include/EventLoop.h
> +/**
Move to it's own file

2024-09-24 09:21 UTC, murillo128 commented on include/EventLoop.h
> +class SystemPoll : public Poll
Do we have any other kinf of Poll different than the SystemPoll?

2024-09-24 22:45 UTC, harryz2000 commented on include/EventLoop.h
> +class SystemPoll : public Poll
Yes. I have created a SrtPoll for SRT server and client. It is in the PR in SRT repo.

2024-09-24 23:22 UTC, harryz2000 commented on include/EventLoop.h
> +	bool AddFd(FileDescriptor fd) override;
I didn't realise we had a FileDescriptor class. Just checked that. It seems created for different purpose. The new FileDescriptor is only for wrap the information while the existing one is for some RATT feature. I would prefer to rename the new one to FileDescriptorInfo or similar to reflect it is very light struct to store some information, contain no logic.

2024-09-25 22:33 UTC, phil-moss-dolby commented on include/Poll.h
> +	enum Event
should we make this be an explicit type?

enum class Event : uint16_t {

2024-09-25 23:11 UTC, harryz2000 commented on include/Poll.h
> +	enum Event
That is a good point. I did think of change it to `enum class`, however that made it difficult to do bitwise operations. Such as:
`auto  events = Poll::Event::In | Poll::Event::Out;`
would become:
`auto events = static_cast<std::underlying_type<Poll::PollFd::Category>::type>(Poll::Event::In) | static_cast<std::underlying_type<Poll::PollFd::Category>::type>(Poll::Event::Out);`

It is very long and the readability looks not good to me. The reason as this enum is basically used as flags for bitwise calculation. It is a bit different to normal enumerations. We could change those to constants, but I feel Using a enum is to make code more organised. If the worries is the enum value could exceed 16bits, I can add a static_assert to it.

2024-09-25 23:20 UTC, harryz2000 commented on include/Poll.h
> +	enum Event
Actually I can specify uint16_t for a enum as well without use of class. Changed.

2024-09-26 08:08 UTC, murillo128 requested changes

2024-09-26 08:08 UTC, murillo128 commented on src/EventLoop.cpp
> +				auto events = poll->GetEvents(pfd);
why can't we return the error as an event?

2024-09-26 08:08 UTC, murillo128 commented on src/EventLoop.cpp
> +				if (error)
I would prefer the nesting

```
switch (pdf.category)
{
  case Poll::PollFd::Category::Signaling:
  {
    if (error)
     .....
  }
  case Poll::PollFd::Category::IO
  {
  }
}

```

2024-09-26 08:08 UTC, murillo128 commented on src/EventLoop.cpp
> +	if (!poll->AddFd({Poll::PollFd::Category::Signaling, pipe[0]}))
should the signaling pipe be managed inside the poll object itself?

2024-09-26 08:08 UTC, murillo128 commented on src/rtmp/rtmpclientconnection.cpp
> +	blocksignals();
should this be done inside the poll object insted?

2024-09-26 23:53 UTC, harryz2000 commented on src/EventLoop.cpp
> +	auto cleanUp = std::make_shared<ScopedCleanUp>([this](){
I am doing the clean up in this way to clean up whenever this function returns upon an error or when the thread loop exits if it is started. Note previously we didn't close the all pipes if one pipe is invalid. For example the code at line 193, it should be:
```
    if (pipe[0]==FD_INVALID || pipe[1]==FD_INVALID)
   {
             if (pipe[0] != FD_INVALID) close(pipe[0));
             if (pipe[1] != FD_INVALID) close(pipe[1));

            return Error("...");
   }

```
We basically need to this for every error cases. Using the ScopedCleanUp would make this kind of handling easier.

2024-09-26 23:56 UTC, harryz2000 commented on src/EventLoop.cpp
> +	if (!poll->SetEventMask({Poll::PollFd::Category::Signaling, pipe[0]}, Poll::Event::In))
The code assume fd is unique if category is different. For example, For IO fd, there could be a 1. For Signaling FD, there could be a 1 as well. Only passing a fd would give the Poll enough information to indentify which PollFd it is refering. Basically for Poll class, the catagory+fd identify an entry.

2024-09-27 00:02 UTC, harryz2000 commented on src/EventLoop.cpp
> +	if (!poll->AddFd({Poll::PollFd::Category::Signaling, pipe[0]}))
Initially I thought of that way. I even created a SignallingPoll class. But eventually I choose to make in the EvenLoop since that would make the Poll class interface not clean. For example, I would need to add interfaces such as Signal(), CleanSignal(). That is kind of against the idea to only abstract the pure Poll interfaces rather than adding specific fd related functionality. 

Basically the idea is the Poll class only care about the generic poll infrastructure, i.e. how to implement the poll. The specific usage of the Poll should be in other classes. For our case, only the EvenLoop is using the signalling, which is part of the EventLoop functionality. So I leave the code there.

2024-09-27 00:03 UTC, harryz2000 commented on include/EventLoop.h
> +	inline bool RemoveFd(int fd)
OK

2024-09-27 00:03 UTC, harryz2000 commented on include/EventLoop.h
> +	inline bool AddFd(int fd, std::optional<uint16_t> eventMask = std::nullopt)
OK

2024-09-27 00:03 UTC, harryz2000 commented on include/EventLoop.h
> +	inline void ForEachFd(const std::function<void(int)>& func)
OK

2024-09-27 00:09 UTC, harryz2000 commented on src/NetEventLoop.cpp
> +			//Set incoming socket cpu affinity
Actually the pfd here is a pure fd. I should make it clearer here. As the EvenLoop virtual functions  only handle IO category of fds. The base EvenLoop handle the signalling one. So here he EvenLoop::ForEachFd only call functions on IO categories.

The Idea is the signaling category of fd is private in base EventLoop. So the subclasses doesn't need to handle its logic.

2024-09-27 00:10 UTC, harryz2000 commented on src/NetEventLoop.cpp
> +	return sending.size_approx() ? (Poll::Event::In | Poll::Event::Out) : Poll::Event::In;
The are automatically added to the event mask in SystemPoll implementation as we need them all the time.

2024-09-27 00:19 UTC, harryz2000 commented on src/NetEventLoop.cpp
> +	throw std::runtime_error("Error occurred on network fd: " + errorMsg);
The exception throwing here is to make the EventLoop to exit. There is a try-catch section in EventLoop::Run() that contains the code to call OnPollError().  The OnPollError is an event handling already, yes. However, this error might not be fatal. 

For example, for SRTPoll, a OnPollError on one file descriptor might just mean one SRT connection is broken. In that case, we only want to drop the connection and keep the server thread running so we wouldn't throw exception for that case.

Or maybe I misunderstood the comment?

2024-09-27 00:32 UTC, harryz2000 commented on src/EventLoop.cpp
> +				auto events = poll->GetEvents(pfd);
We could. However I prefer to separate it as especially I am expecting the poll can return an error message in case of an error. Performance-wise, using different functions would be similar. 

Plus for different Polls, the error might be got in different ways, i.e. SRTPoll would need to call functions such as srt_getsockstate(). Splitting it would be neater to me. 

For SystemPoll, we stores the events flags after wait(). So we can easily just read the flags and check the bit, which we would need to do anyway.

2024-09-27 00:32 UTC, harryz2000 commented on src/EventLoop.cpp
> +				if (error)
OK

2024-09-27 01:12 UTC, harryz2000 commented on src/rtmp/rtmpclientconnection.cpp
> +	blocksignals();
For existing code, I see it called when the thread starts. I kind of kept the logic. If we want to move it to poll, it seems we would call this function multiple times unless we only add it to Poll constructor. 

Or maybe we should add it to the EvenLoop() start functions? i.e. always block the signals before starting a thread. Basically all threads would have the signals blocked.

2024-09-27 01:25 UTC, harryz2000 commented on src/EventLoop.cpp
> +	if (pipe[0]!=FD_INVALID) close(pipe[0]);
Yes. We can. We still need to manually reset the FileDescriptor when doing cleanUp though.

2024-09-30 16:17 UTC, murillo128 requested changes

2024-09-30 23:49 UTC, harryz2000 commented on src/SystemPoll.cpp
> +	if (tempfdsDirty)
This temporary fds is to allow the callback to remove a fd. Otherwise, the callback cannot call RemoveFd(). i.e. the following code would cause crash:

```
for (auto fd : fds)
{
      fds.erase(fd);
}
```

2024-09-30 23:51 UTC, harryz2000 commented on include/EventLoop.h
> +	std::unique_ptr<FileDescriptor>	pipeFds[2];
OK. I will try to remove the clean up use.

2024-09-30 23:53 UTC, harryz2000 commented on src/EventLoop.cpp
> +			if (pfd.category == Poll::PollFd::Category::Signaling) return;
The `EventLoop::ForEachFd(int fd)` only provide IO fds. However, `Poll::ForEachFd(PollFd pfd)` will provide both IO and Signalling, this is to hide the signalling part from the users.

2024-09-30 23:56 UTC, harryz2000 commented on src/EventLoop.cpp
> +				case Poll::PollFd::Category::Signaling:
As above, EventLoop::ForEachFd() is different to Poll::ForEachFd(). The argument type is different. It happens the function name is same. Potentially the first one could be renamed to EventLoop::ForEachIOFd()?

2024-10-01 00:01 UTC, harryz2000 commented on src/EventLoop.cpp
> +						OnSignallingError(*error);
I don't think we can recover from signalling error. But for some existing code, it seems the error was just ignored. But yes, we should exit on the error.

About exiting the thread, actually I think we may want to think what should we do if the thread exits. Such as when a SRT server thread exits, it couldn't accept new SRT requests. But that would be out of current PR's scope.

2024-10-01 01:05 UTC, harryz2000 commented on src/EventLoop.cpp
> +				auto error = poll->GetError(pfd);
We could change to that way. But I personally don't like to add event masks for errors, as we always need to add errors. For SRTPoll, we even don't have a way to enable/disable the error mask as it is always reported. And we still need to report error messages. So we need still have following functions.

```
uint64_t GetEvents(fd);
std::string GetErrorMessage(fd);
```
Or:

`std::pair<uint64_t, std::string> GetEvents(fd);`

2024-10-01 03:26 UTC, harryz2000 commented on include/EventLoop.h
> +	std::unique_ptr<FileDescriptor>	pipeFds[2];
I changed to clear the registered fds before adding signalling fd so we can remove the clean up.
The purpose is to make the Start() can be called multiple times without duplicated fd adding.

2024-10-01 03:29 UTC, harryz2000 commented on src/EventLoop.cpp
> +				case Poll::PollFd::Category::Signaling:
I was trying to hide the category part for EventLoop users. But happy to change the EventLoop member functions to:
AddIOFd()
RemoveIOFd()
ForEachIOFd()

2024-10-01 03:36 UTC, harryz2000 commented on src/EventLoop.cpp
> +				auto error = poll->GetError(pfd);
I would prefer to use the second format:
`std::pair<uint16_t, std::string> GetEvents(fd);`
Or:
`std::variant<uint16_t, std::string> GetEvents(fd);`
While I still keep only two event types. The error would be returned as an string, rather than a flag.
```
enum Event
{
  In = 0x1,
  Out = 0x2,
};
```
How do think?

2024-10-01 03:46 UTC, harryz2000 commented
> that pattern is really ackwards, exception handling should only be used for exceptional error handling not flow control.

The exception means we need to exit the thread. To me, it can be thought of an exceptional case. Normally we don't want to exit the thread. 

There are potential other ways:
1. Return different value, such as bool. such as `bool OnPollError()`, this is sometimes confusing.
2. Passing a reference to capture the intended behaviour from callbacks, such as void OnPollError(bool& exit);

The options might not be as clean as the exception.

2024-10-01 05:15 UTC, harryz2000 commented
> > that pattern is really ackwards, exception handling should only be used for exceptional error handling not flow control.
> 
> The exception means we need to exit the thread. To me, it can be thought of an exceptional case. Normally we don't want to exit the thread.
> 
> There are potential other ways:
> 
> 1. Return different value, such as bool. such as `bool OnPollError()`, this is sometimes confusing.
> 2. Passing a reference to capture the intended behaviour from callbacks, such as void OnPollError(bool& exit);
> 
> The options might not be as clean as the exception.

I would prefer to use option 2 if not using exception. Any suggestions?

2024-10-01 06:50 UTC, murillo128 commented on src/EventLoop.cpp
> +						OnSignallingError(*error);
but it would be notified on the loop exit callback, right?

2024-10-01 06:57 UTC, harryz2000 commented on src/EventLoop.cpp
> +						OnSignallingError(*error);
Yeah. We could use the loop exit callback. But currently that callback doesn't contain the error code unless we store the error code somewhere, which we could do. I thought of that. It is actually possibly cleaner. However I feel that change would be kind of out of current scope. Not sure we should do the change under current PR.

2024-10-01 20:07 UTC, yezhan10 commented on include/Poll.h
> +		return (uint64_t(static_cast<std::underlying_type<Poll::PollFd::Category>::type>(fd.category)) << 32) + uint32_t(fd.fd);
maybe consider to use std::underlying_type_t for better readability?

2024-10-01 21:21 UTC, yezhan10 commented on src/EventLoop.cpp
> +	// Remove all signaling fds
why the comment says remove all signaling fds? should this ForEachFd() remove both IO and Signaling fds?

2024-10-01 21:27 UTC, yezhan10 commented on include/Poll.h
> +		return (uint64_t(static_cast<std::underlying_type<Poll::PollFd::Category>::type>(fd.category)) << 32) + uint32_t(fd.fd);
Or maybe worth of creating something like this?: 
`template<typename E>
constexpr auto
	toUType(E enumerator) noexcept
	{
		return static_cast<std::underlying_type_t<E>>(enumerator);
	}`

2024-10-02 00:57 UTC, harryz2000 commented on include/Poll.h
> +		return (uint64_t(static_cast<std::underlying_type<Poll::PollFd::Category>::type>(fd.category)) << 32) + uint32_t(fd.fd);
Would change to std::underlying_type_t. 
I probably wouldn't add the help function as currently it is just used in very few places.

2024-10-02 00:58 UTC, harryz2000 commented on include/Poll.h
> +	enum Event : uint16_t
As discussed, it is used as constants. I would prefer to use the unscoped one here for easy to calculate.

2024-10-02 06:01 UTC, harryz2000 commented on src/EventLoop.cpp
> +	// Remove all signaling fds
Good catch! Indeed I meant to remove signaling fds. Other fds would be managed by user.

2024-10-02 07:01 UTC, murillo128 commented on src/EventLoop.cpp
> +						OnSignallingError(*error);
we have added those callbacks in this PR, so we can do wathever we want

2024-10-02 07:03 UTC, murillo128 commented on src/SystemPoll.cpp
> +	if (tempfdsDirty)
I don't think we should allow the callback to modify the fds

2024-10-02 12:44 UTC, harryz2000 commented on src/EventLoop.cpp
> +	pipeFds[0] = FileDescriptor(pipe[0]);
The move is not necessary as the FileDescriptor is already an RValue. I think assigning a int to the FileDescriptor wouldn't work as it doesn't have a operator=(int) override. But I will try.

2024-10-02 12:47 UTC, harryz2000 commented on src/EventLoop.cpp
> +			(void)poll->RemoveFd(pfd);
Because I don't want to clean all fds. It is not illegal to add fd first and then call the Start() function. For example,
```
loop->AddFd(fd);
loop->Start();
loop->Stop();
loop->Start();
```
I don't want the Start() to clear the added fd by caller. It only clears the signaling one it added.

2024-10-02 12:49 UTC, harryz2000 commented
> I don't think we should allow the callback to modify the fds
But we do need to remove for SRTPoll. Such as when it receive an OnPollError() it means the SRT socket was closed. We need to remove it from the map. Any idea to do that?

2024-10-02 12:52 UTC, harryz2000 commented on include/ScopedCleanUp.h
> +#ifndef SCOPEDCLEANUP_H
yep

2024-10-02 12:54 UTC, harryz2000 commented on src/SystemPoll.cpp
> +	if (tempfdsDirty)
But we do need to remove for SRTPoll. Such as when it receive an OnPollError() it means the SRT socket was closed. We need to remove it from the map. Any idea to do that?

2024-10-02 13:07 UTC, murillo128 requested changes

2024-10-02 13:07 UTC, murillo128 commented on src/EventLoop.cpp
> +	pipeFds[0] = FileDescriptor(pipe[0]);
are you sure that we are not going to `dup` the `fd` if not moving?

2024-10-02 13:07 UTC, murillo128 commented on src/EventLoop.cpp
> +			(void)poll->RemoveFd(pfd);
```suggestion
			poll->Clear(Poll::PollFd::Category::Signaling);
```

2024-10-02 13:07 UTC, murillo128 commented on src/EventLoop.cpp
> +			if (pfd.category == Poll::PollFd::Category::Signaling) return;
add a filtering criteria for `ForEachFd` then better

2024-10-02 13:07 UTC, murillo128 commented on src/EventLoop.cpp
> +				auto error = poll->GetError(pfd);
we should not report errors as strings

2024-10-02 13:20 UTC, harryz2000 commented on src/EventLoop.cpp
> +	if (!poll->SetEventMask({Poll::PollFd::Category::Signaling, pipe[0]}, Poll::Event::In))
Take SRT for example, I am not sure a SRTSocket value would be possibly same as an signalling fd value. That is why a category is used to tell which type it is.

2024-10-02 13:21 UTC, harryz2000 commented on src/EventLoop.cpp
> +	poll->ForEachFd([this](Poll::PollFd pfd){
Would change to this way.

2024-10-02 22:40 UTC, murillo128 commented
one thing I was thinking,  is there any reason why we have to injection the signaling pipe from the evenloop and not handle it inside the Poll directly?

the only thing that the evenloop needs is a way to mask the poll wait to exit.

2024-10-02 23:11 UTC, harryz2000 commented
> one thing I was thinking, is there any reason why we have to injection the signaling pipe from the evenloop and not handle it inside the Poll directly?
> 
> the only thing that the evenloop needs is a way to mask the poll wait to exit.

Good thought. Yes. We could optimise this even further. One question is if there is another way other than using a signalling fd for break the poll. I didn't investigate too much about that yet as I wanted to limit the scope of the change. If there is no other way, we could create a class such as SignallingPoll<SystemPoll> to wrap the signalling part. But that is basically a duplication of the logic in EventLoop. I still think the basic Poll interface shouldn't have a Signal/ClearSignal function because it is the most basic functionality. For example the SignalingPoll could be a template class to add the new functions:

```
template<typename PollClass>
class SignallingPoll : public PollClass
{
public:
       void Signal();
       void ClearSignal();
};
```

2024-10-02 23:16 UTC, murillo128 commented
my point was about moving the eventfd inside the poll object,  it is only used fircsignaling the poll to exit the wait function,  so no sure why it needs to be setup at the event loop

2024-10-02 23:26 UTC, harryz2000 commented
> my point was about moving the eventfd inside the poll object, it is only used fircsignaling the poll to exit the wait function, so no sure why it needs to be setup at the event loop

The main rationale is the Poll interface is to abstract the basic poll functions for system poll and SRT poll. Both the system poll and SRT poll functions don't have the functions to break the wait, as far as I could see for now.

If we want to break the wait, i.e. by adding signalling, that is something functionality we are adding to the basic functionality. So as per the rationale I put the logic into another class as the functionality is an add-on. This class can be a separate class such as SignallingPoll. It is just currently it is in EventLoop.

Does it makes sense?

2024-10-02 23:36 UTC, murillo128 commented
I don't think we need so many abstraction layers providing no actual benefit.  We could have some helpers to avoid duplicating code, but I don't see the value of the SignallingPoll

2024-10-02 23:38 UTC, harryz2000 commented
> I don't think we need so many abstraction layers providing no actual benefit. We could have some helpers to avoid duplicating code, but I don't see the value of the SignallingPoll

OK. I can move the code to the Poll base class then.

2024-10-03 04:19 UTC, harryz2000 commented on src/EventLoop.cpp
> +	pipeFds[0] = FileDescriptor(pipe[0]);
Confirmed. As above mentioned, it would only trigger the move assign, wouldn't call dup.

2024-10-03 04:21 UTC, harryz2000 commented on src/EventLoop.cpp
> +			(void)poll->RemoveFd(pfd);
Added a Setup function in Poll() to only add signaling fd if not setup.

2024-10-03 04:35 UTC, harryz2000 commented on include/Poll.h
> +		return (uint64_t(static_cast<std::underlying_type<Poll::PollFd::Category>::type>(fd.category)) << 32) + uint32_t(fd.fd);
added the helper function. After changing the way to set exit loop code. Conversion from an scoped enum becomes more.

2024-10-03 04:41 UTC, harryz2000 commented on src/EventLoop.cpp
> +			if (pfd.category == Poll::PollFd::Category::Signaling) return;
done

2024-10-03 04:42 UTC, harryz2000 commented on src/EventLoop.cpp
> +						OnSignallingError(*error);
I added a SetStopping(exitCode) in EventLoop to flag the thread needs to be stopped.

2024-10-03 04:43 UTC, harryz2000 commented on src/EventLoop.cpp
> +				auto error = poll->GetError(pfd);
Change the function to :
`std::pair<uint16_t, int> GetEvents(fd);`
The first of the returned pair is events flags, the second is error code.

2024-10-03 04:43 UTC, harryz2000 commented on src/EventLoop.cpp
> +	if (!poll->AddFd({Poll::PollFd::Category::Signaling, pipe[0]}))
Done

2024-10-03 09:45 UTC, murillo128 requested changes

2024-10-03 09:45 UTC, murillo128 commented on src/Poll.cpp
> +bool Poll::Setup()
why can't this happen on constructor?

2024-10-03 09:45 UTC, murillo128 commented on include/Poll.h
> +	void Signal();
I would prefer to keep this functions pure virtual and move the pipe to the SystemPoll instead

2024-10-03 09:45 UTC, murillo128 commented on include/Poll.h
> +	virtual bool AddFd(PollFd::Category category, int fd) = 0;
as we are moving the pipe to the SystemPoll, there is no need to have the `PollFd::Category` anymore

2024-10-03 12:42 UTC, harryz2000 commented on src/Poll.cpp
> +bool Poll::Setup()
because it requires to call virtual functions, which cannot be called in constructor.

2024-10-03 12:44 UTC, harryz2000 commented on include/Poll.h
> +	void Signal();
So we duplicate the code in SRTPoll? The SRTPoll would use same logic.

2024-10-03 12:47 UTC, harryz2000 commented on include/Poll.h
> +	virtual bool AddFd(PollFd::Category category, int fd) = 0;
It seems you would like to implement SystemPoll and SRTPoll separately by duplicating the signalling logic?

2024-10-03 13:02 UTC, murillo128 commented on src/Poll.cpp
> +bool Poll::Setup()
I mean, if we move the pipe to the SystemPoll, we can move this to its constructor.

2024-10-03 13:03 UTC, murillo128 commented on include/Poll.h
> +	void Signal();
yes, duplication would be minimal. You can create a SignalingPipe helper class to wrap the eventfd/pipe creation

2024-10-03 13:05 UTC, murillo128 commented on include/Poll.h
> +	virtual bool AddFd(PollFd::Category category, int fd) = 0;
SRTPoll is already a separate class, what I want to avoid is to have to deal with the signaling at the EventLoop level

2024-10-03 13:06 UTC, harryz2000 commented on include/Poll.h
> +	void Signal();
OK. It is not my personal preference but happy to do that.

2024-10-03 13:06 UTC, harryz2000 commented on include/Poll.h
> +	virtual bool AddFd(PollFd::Category category, int fd) = 0;
OK

2024-10-04 07:21 UTC, murillo128 requested changes

2024-10-04 07:21 UTC, murillo128 commented on src/EventLoop.cpp
> +		auto [events, error] = poll->GetSignallingEvents();
could we return the error better directly on the `Wait()` ?

2024-10-04 07:21 UTC, murillo128 commented on src/EventLoop.cpp
> +			SetStopping(ToUType(PredefinedExitCode::SignalingError));
shouldn't we exit on error?

2024-10-04 07:21 UTC, murillo128 commented on src/EventLoop.cpp
> +		auto [events, error] = poll->GetSignallingEvents();
we don't need the events from the signaling pipe at all, right?

2024-10-04 07:21 UTC, murillo128 commented on src/EventLoop.cpp
> +			poll->ClearSignal();
shouldn't we better clear the signal last as it was done on the original code?

2024-10-04 07:21 UTC, murillo128 commented on src/SystemPoll.cpp
> +	if (sysfdsDirty)
as we are not iterating over the syspfds, there is no reason to have a separate vector for that, right?

2024-10-07 22:22 UTC, harryz2000 commented on src/EventLoop.cpp
> +		auto [events, error] = poll->GetSignallingEvents();
No. I can remove the events

2024-10-07 22:25 UTC, harryz2000 commented on src/EventLoop.cpp
> +			SetStopping(ToUType(PredefinedExitCode::SignalingError));
Yes. It would exit. The SetStopping would cause the thread exit. Or could you clarify the comment?

2024-10-07 22:28 UTC, harryz2000 commented on src/EventLoop.cpp
> +			poll->ClearSignal();
It seems to me it wouldn't impact too much as we would exit anyway. I will move it later along changing the GetSignalEvents() return value.

2024-10-07 22:39 UTC, harryz2000 commented on src/SystemPoll.cpp
> +	if (sysfdsDirty)
The syspfds is used for poll() function to retrieve events. As for managing the fds, we use a map rather than an array. So we have to convert it to an array (vector) before calling the poll() function. The flag sysfdsDirty is to ensure the vector is only recreated when something changed.  I couldn't we could remove it. Or I missed anything?

2024-10-08 04:11 UTC, harryz2000 commented on src/EventLoop.cpp
> +		auto [events, error] = poll->GetSignallingEvents();
I further removed the GetSignallingEvents(), and added the logic to the wait function. 
Also removed the ClearSignal function, now the clear is automatically done in the wait function.

2024-10-08 04:14 UTC, harryz2000 commented on src/EventLoop.cpp
> +			poll->ClearSignal();
Moved the clear to Wait() function so it would be automatically cleared. I don't see the clear has to be after the Error logging and set stopping function. Making the ClearSignal() in wait function make the interface simpler to me.

2024-10-08 22:59 UTC, harryz2000 commented on src/Poll.cpp
> +bool Poll::Setup()
Done

2024-10-09 03:17 UTC, bcostdolby commented on src/PollSignalling.cpp
> +	one = write(pipeFds[1],(uint8_t*)&one,sizeof(one));
Just curious why we need to write a 64bit int and not just 1 byte?

2024-10-09 03:17 UTC, bcostdolby commented on src/PollSignalling.cpp
> +	one = write(pipeFds[1],(uint8_t*)&one,sizeof(one));
Should we also check for errors on return from write and throw or at least log an error? In theory they probably wont happen but if they do would be very useful to know.

2024-10-09 03:17 UTC, bcostdolby commented on src/PollSignalling.cpp
> +		while (read(pipeFds[0], &data, sizeof(uint64_t)) > 0)
Not all errors are the same. I think we should retry on EINTR at least. Possibly log error on other unexpected errors

2024-10-09 03:17 UTC, bcostdolby commented on src/SystemPoll.cpp
> +		throw std::runtime_error("Failed to add signaling fd to event poll\n");
Worth adding the strerror reason as well as that is more important than the op failed. Why did it fail

2024-10-09 03:17 UTC, bcostdolby commented on src/SystemPoll.cpp
> +		throw std::runtime_error("Failed to set event mask\n");
Worth adding the strerror reason as well as that is more important than the op failed. Why did it fail

2024-10-09 03:17 UTC, bcostdolby commented on src/SystemPoll.cpp
> +				signalling.ClearSignal();
Should we still iterate over all the other items and return at the end?

Some poll events are edge triggered instead of level triggered (not sure we make use of this though) and if we dont handle them we lose valuable information. 

I dont think that we are using any edge triggered events but if we do then this will be broken

2024-10-09 03:26 UTC, harryz2000 commented on include/PollSignalling.h
> +	FileDescriptor pipeFds[2];
Not sure that would be better. I would prefer to leave it as it is.

2024-10-09 03:29 UTC, harryz2000 commented on src/PollSignalling.cpp
> +	one = write(pipeFds[1],(uint8_t*)&one,sizeof(one));
Not sure. Maybe @murillo128 knows the reason. The code was copied from existing code. Again, I would prefer to limit the scope of this PR.

2024-10-09 03:30 UTC, harryz2000 commented on src/PollSignalling.cpp
> +	one = write(pipeFds[1],(uint8_t*)&one,sizeof(one));
As above, the code was copied from existing code. Again, I would prefer to limit the scope of this PR. I would make notes for the comments.

2024-10-09 03:30 UTC, harryz2000 commented on src/PollSignalling.cpp
> +		while (read(pipeFds[0], &data, sizeof(uint64_t)) > 0)
As above, the code was copied from existing code. Again, I would prefer to limit the scope of this PR. I would make notes for the comments.

2024-10-09 03:45 UTC, harryz2000 commented on src/SystemPoll.cpp
> +				signalling.ClearSignal();
I don't see much benefits since we would exit the thread anyway. Event the events was set, the return value is still indicating there is an error. The revents wouldn't be regarded as valid. On the other hand, this error shouldn't happen unless OS got an error.

I don't think we would use edge triggered. As per https://stackoverflow.com/questions/15072165/is-poll-an-edge-triggered-function, it seems the poll function is always level triggered. Epoll might work in different modes. But we are not using Epoll.

2024-10-09 04:26 UTC, harryz2000 commented on include/tools.h
> +	auto sz = std::vsnprintf(nullptr, 0, fmt, ap);
It seems current implementation has no problem. I added the va_start/va_end as it looks that is the right way in theory, yes.

2024-10-09 04:29 UTC, harryz2000 commented on src/SystemPoll.cpp
> +		throw std::runtime_error("Failed to add signaling fd to event poll\n");
Adding more info is always better, yes. I added logs in the function to show the details rather than put it in this exception. I think that would make the interface simpler. Otherwise a error code might not be easy to reflect different situations from different Poll implementations. It would up to the concrete class to log the error details.

2024-10-09 04:29 UTC, harryz2000 commented on src/SystemPoll.cpp
> +		throw std::runtime_error("Failed to set event mask\n");
Adding more info is always better, yes. I added logs in the function to show the details rather than put it in this exception. I think that would make the interface simpler. Otherwise a error code might not be easy to reflect different situations from different Poll implementations. It would up to the concrete class to log the error details.

2024-10-09 05:12 UTC, bcostdolby commented on src/SystemPoll.cpp
> +				signalling.ClearSignal();
Ahh yes. My recollection was from before using epoll.

2024-10-09 05:23 UTC, murillo128 commented on src/PollSignalling.cpp
> +	one = write(pipeFds[1],(uint8_t*)&one,sizeof(one));
eventfd used 8bytes reads/writes

2024-10-09 07:28 UTC, merged

2024-11-04 17:59 UTC, mildsunrise commented on include/FileDescriptor.h
> +		fd = dup(other.fd);
I'm looking at this and don't understand
1. what's wrong with the previous code? it's the [copy and swap idiom](https://stackoverflow.com/a/3279550/710951) and there's usually little reason to change it
2. doesn't the new code fail to close the previous FD, therefore leaking it?

2024-11-04 18:03 UTC, mildsunrise commented on include/FileDescriptor.h
> +		fd = dup(other.fd);
regarding error handling of dup(), the only errors it can raise are EBADF (if the passed descriptor is not open) and EMFILE (if we've reached the limit for open file descriptors in the process). EBADF should never happen unless there's a bug, and if EMFILE happens I'm pretty sure the media server would just collapse entirely so no point in doing anything smart, I'm okay with just asserting and crashing otherwise

2024-11-04 20:36 UTC, bcostdolby commented on src/PollSignalling.cpp
> +	one = write(pipeFds[1],(uint8_t*)&one,sizeof(one));
yeah I read the docs for the event in more detail after writing the comment and forgot to resolve it.

2024-11-04 22:17 UTC, harryz2000 commented on include/FileDescriptor.h
> +		fd = dup(other.fd);
The reason is the previous code:
`FileDescriptor& operator=(FileDescriptor other)`
was not a entirely a copy operator.
It causes compile errors in some cases, i.e. when other is a R value iirc, as the compiler wouldn't know which one it should choose between it and 
`FileDescriptor& operator=(FileDescriptor&& other)`
While as a copy assignment, it should not accept a R value. And it functionality should be same as copy constructor. 
`FileDescriptor(const FileDescriptor& other)`
Otherwise, it would surprise the users.
https://en.wikipedia.org/wiki/Rule_of_three_(C%2B%2B_programming)#Rule_of_five

2024-11-04 22:53 UTC, mildsunrise commented on include/FileDescriptor.h
> +		fd = dup(other.fd);
thanks, that explains it. shouldn't we just remove `FileDescriptor& operator=(FileDescriptor&& other)` then?
as the post I linked explains, `FileDescriptor& operator=(FileDescriptor other)` acts as both a copy operator and a move operator, because the compiler will move construct into `FileDescriptor other` if it's an rvalue

2024-11-04 23:10 UTC, harryz2000 commented on include/FileDescriptor.h
> +		fd = dup(other.fd);
That might resolve the compiling issue, yes. However I think it is unusual to do that way and it may not be good for performance. For rule of five, all the five functions should be declared explicitly. Using `FileDescriptor& operator=(FileDescriptor other)` for both L and R values would introduce unnecessary constructing:

For example, when it is assigned an R value, it would call:
```
FileDescriptor(FileDescriptor&&)
FileDescriptor& operator=()
```
when it is assigned to a L value, it would call:
```
FileDescriptor(const FileDescriptor&)
FileDescriptor& operator=()
```
If we declare` operator=` for L and R value separately, the constructor wouldn't be called.

2024-11-05 02:54 UTC, mildsunrise commented on include/FileDescriptor.h
> +		fd = dup(other.fd);
the copy-and-swap idiom [is](https://www.geeksforgeeks.org/copy-swap-idiom-c/) [fairly](https://en.wikibooks.org/wiki/More_C%2B%2B_Idioms/Copy-and-swap) [popular](https://www.reddit.com/r/cpp/comments/1am9jzm/copy_and_swap_idiom/). it is *much* less error prone (especially with pitfalls of assigning something to itself, or forgetting to free current resources like what happened here), less code to write, and provides strong exception safety.

> it may not be good for performance

don't underestimate compilers! conceptually you may be calling those 2 things (the constructor and the assign operator) but the compiler knows the definition of both and can [elide everything away, so no intermediary object is actually created in memory](https://godbolt.org/z/P3hYTsWcT).

for objects that can re-use its existing resources (like allocations) to host the copy, then copy-and-swap can be wasteful, but that doesn't apply here.

2024-11-05 03:31 UTC, harryz2000 commented on include/FileDescriptor.h
> +		fd = dup(other.fd);
Thanks for providing the examples. Yes. It is not a surprise that the compiler could optimise the code to very deep level. The idiom looks elegant and no performance impact in some cases. My concern is the benefit, especially the performance impact, might not apply to all the classes. imho, it would be better to have consistent code style so it could be easily reviewed and the behaviour would be more predictable. For this specific case, I agree the copy-and-swap would work.

2024-11-05 12:26 UTC, mildsunrise commented on include/FileDescriptor.h
> +		fd = dup(other.fd);
we can have a vote on this, but given how tricky it is to implement everything in the rule of five correctly, my stance is to always do copy-and-swap except on those specific cases where there is a performance impact and it is high enough... because every single time I've reviewed a RAII class that was not using copy-and-swap, the assignment operator was not implemented correctly