add unit tests for h264 sps/pps parsing
medooze/media-server pull request #351
Opened 2024-09-26 21:59 UTC by amaha877

Adding some tests for h264 sps pps parsing

2024-09-26 22:01 UTC, amaha877 commented
I've encapsulated the sps/pps data in structs so that its easy for the tests to validate (instead of relying on stdout `Dump()` )

2024-09-26 22:02 UTC, murillo128 commented on src/h264/h264.h
> -			printf("0x%x, ", buffer[i]);
you can use 

::Dump(buffer, bufferSize)

instead

2024-09-26 22:05 UTC, murillo128 requested changes

2024-09-26 22:05 UTC, murillo128 commented on src/h264/h264.h
> +	}data;
moving all the attributes to an internal field is not in scope of this task, please keep changes to the minimum for easier review and not disruption othe codebasr

2024-09-26 22:08 UTC, murillo128 commented
better either make the attributes public or try adding the test class as friend (not sure if possible)

2024-09-26 22:17 UTC, amaha877 commented on src/h264/h264.h
> +	}data;
Okay, I'll make it public.

2024-09-26 22:27 UTC, murillo128 commented on src/h264/h264.h
> +	BYTE			profile_idc = 0;
could you move back this code block to its previous position? it is harder to review if I have to go line by mine to verify if there has been any unintended change committed

2024-09-26 23:35 UTC, murillo128 approved these changes
lgtm

2024-09-27 05:34 UTC, amaha877 commented
Added the fixes. @murillo128 please take a look.

2024-09-27 05:36 UTC, amaha877 commented on include/bitstream/BitReader.h
> +		return codeNum & 0x01 ? (codeNum+1) >> 1 : -(codeNum >> 1);
Verified this with libav as well as h264NAL tool

2024-09-27 05:38 UTC, amaha877 commented on src/h264/H26xNal.h
> +		if (!num) return;
if we don't do this check, we keep incrementing the position of the read pointer and eventually overflow the entire buffer and thereby causing an exception. So if we haven't consumed any whole bytes, then nothing to Skip.

2024-09-27 07:53 UTC, merged