Draft: MPEGTS encoding and packetization. Prepare for SRT Client implementation.
medooze/media-server pull request #353
Opened 2024-09-27 06:05 UTC by harryz2000

2024-09-27 06:08 UTC, harryz2000 commented
I am planning to add more unit tests.

2024-09-30 16:15 UTC, murillo128 requested changes

2024-09-30 16:15 UTC, murillo128 commented on src/EventLoop.cpp
> +	if (std::this_thread::get_id()==thread.get_id() || signaled.test_and_set() || !pipeFds[1])
this shouldn't be here

2024-09-30 16:15 UTC, murillo128 commented on src/FrameDelayCalculator.cpp
> - * @return The timestamp basing on the target clock rate
this change does not belong here

2024-09-30 16:15 UTC, murillo128 commented on src/mpegts/psi.cpp
> -std::vector<Table> ParsePayloadUnit(BufferReader& reader)
why has this been removed?

2024-09-30 16:15 UTC, murillo128 commented on src/mpegts/psi.cpp
> -std::vector<ProgramAssociation> ProgramAssociation::ParsePayloadUnit(BufferReader& reader)
why has this been removed?

2024-09-30 16:15 UTC, murillo128 commented on include/Packetizer.h
> +#ifndef PACKETIZER_H
this seems too mpegts specific

2024-09-30 16:15 UTC, murillo128 commented on include/Encodable.h
> +	virtual void Encode(BufferWritter& writer) const = 0;
We have always been called this method `Serialize`

2024-09-30 16:15 UTC, murillo128 commented on include/Encodable.h
> +	virtual size_t Size() const = 0;
Also, we have called this method `GetSize()`

2024-09-30 16:15 UTC, murillo128 commented on include/Encodable.h
> +class Encodable
`Serializable` seems a better name

2024-10-01 00:48 UTC, harryz2000 commented on src/mpegts/psi.cpp
> -std::vector<ProgramAssociation> ProgramAssociation::ParsePayloadUnit(BufferReader& reader)
The code is not used at the moment and I think it was causing a issue in my development.  I would add it back as it seems no problem any more.

2024-10-01 00:48 UTC, harryz2000 commented on include/Encodable.h
> +	virtual void Encode(BufferWritter& writer) const = 0;
OK. Will rename

2024-10-01 00:49 UTC, harryz2000 commented on include/Encodable.h
> +	virtual size_t Size() const = 0;
OK

2024-10-01 00:49 UTC, harryz2000 commented on include/Encodable.h
> +class Encodable
OK

2024-10-01 00:52 UTC, harryz2000 commented on include/Packetizer.h
> +#ifndef PACKETIZER_H
I tried to make it generic. Currently it works for mpegts specifically. However, it could be used for any Messages that implements the Encodable/Serializable interface. We could see if we need to make it more generic when we found other use cases

2024-10-01 00:53 UTC, harryz2000 commented on src/EventLoop.cpp
> +	if (std::this_thread::get_id()==thread.get_id() || signaled.test_and_set() || !pipeFds[1])
Could you clarify this comment? thx

2024-10-01 00:54 UTC, harryz2000 commented on src/FrameDelayCalculator.cpp
> - * @return The timestamp basing on the target clock rate
It seems this is a change for another PR. will fix

2024-10-01 06:45 UTC, murillo128 commented on src/EventLoop.cpp
> +	if (std::this_thread::get_id()==thread.get_id() || signaled.test_and_set() || !pipeFds[1])
I mean that this change is not related to mpegts encoding, probably a bad rebase or similar

2024-10-01 06:46 UTC, murillo128 commented on include/Packetizer.h
> +#ifndef PACKETIZER_H
I mean, that I don't see it usable for anything different than mpegts encoding, probably would need to wait until the SRT PR is ready for review to see how it is used

2024-10-01 07:01 UTC, harryz2000 commented on src/EventLoop.cpp
> +	if (std::this_thread::get_id()==thread.get_id() || signaled.test_and_set() || !pipeFds[1])
That is right. It should belong to another PR :)

2024-10-01 23:48 UTC, yezhan10 commented on include/Packetizer.h
> +		static_assert(std::is_base_of_v<Serializable, T>);
do you think something like this is better?
`template<typename T, typename = std::enable_if_t<std::is_base_of_v<Serializable, std::decay_t<T>>>>`
This will force the T to be derived from Serializable as well? But i am not sure which error message is better in case of misuse.

2024-10-02 00:40 UTC, harryz2000 commented on include/Packetizer.h
> +		static_assert(std::is_base_of_v<Serializable, T>);
Yes. That should work as well and probably better in some way. However for code readability, I feel the static_assert is even easier to read. Ideally, we should use concepts for that. But we have to upgrade to C++ 20 for it.
```
template <typename T> requires std::derived_from<T, Serializable>
```
For now, I would prefer to leave it as it is.

2024-10-02 00:57 UTC, yezhan10 commented on include/Packetizer.h
> +		static_assert(std::is_base_of_v<Serializable, T>);
did not know that c++20 would do something like that, thanks for sharing the info!

2024-10-02 01:08 UTC, harryz2000 commented on include/Packetizer.h
> +#ifndef PACKETIZER_H
Yeah. I will soon make the srt PR available. You can review this code after that. I would prefer keep this code in current PR to avoid frequent branch switching/merging.

2024-10-02 06:03 UTC, harryz2000 commented on src/EventLoop.cpp
> +	if (std::this_thread::get_id()==thread.get_id() || signaled.test_and_set() || !pipeFds[1])
fixed

2024-10-02 07:33 UTC, murillo128 commented on src/mpegts/psi.cpp
> -	syntaxData.crc32		= reader.Get4();
what has happened to the `crc32`?

2024-10-02 07:34 UTC, murillo128 commented on src/mpegts/psi.cpp
> -std::vector<ProgramAssociation> ProgramAssociation::ParsePayloadUnit(BufferReader& reader)
please, don't resolve the conversation until you add this code back

2024-10-02 12:59 UTC, harryz2000 commented on src/mpegts/psi.cpp
> -std::vector<ProgramAssociation> ProgramAssociation::ParsePayloadUnit(BufferReader& reader)
Ah. I added back the` std::vector<Table> ParsePayloadUnit(BufferReader& reader);` one. I thought it was this one. Sorry. Will add this one back as well.

2024-10-02 13:05 UTC, harryz2000 commented on src/mpegts/psi.cpp
> -	syntaxData.crc32		= reader.Get4();
It was moved to the Table pasing. The CRC32 is not only for the syntax data part.
https://github.com/medooze/media-server/blob/beebaddd5964c6466c687e771d7ada01001202fc/src/mpegts/psi.cpp#L192
This is to make SyntaxData encoding is consistent with parsing. See:
https://github.com/medooze/media-server/blob/beebaddd5964c6466c687e771d7ada01001202fc/src/mpegts/psi.cpp#L127

2024-10-03 04:59 UTC, harryz2000 commented on src/mpegts/psi.cpp
> -std::vector<ProgramAssociation> ProgramAssociation::ParsePayloadUnit(BufferReader& reader)
added back

2024-10-03 10:31 UTC, murillo128 commented on include/Packetizer.h
> + * @tparam T The message type. It must be derived from Serializable.
if it must be derived from `Serializable` why do we need it as template variable?

2024-10-03 11:12 UTC, murillo128 commented on include/Packetizer.h
> +	virtual size_t GetNextPacket(BufferWritter& writer)
this method does not Get anything, rename to `SerializeNextPacket` or `WriteNextPacket` or similar

2024-10-03 11:32 UTC, murillo128 commented on include/Packetizer.h
> +#ifndef PACKETIZER_H
after reviewing the srt PR, I don't feel that this class has any meaning outside of it, I am not even sure if it should not be just integrated inside the outgoing stream code directly.

2024-10-03 12:38 UTC, harryz2000 commented on include/Packetizer.h
> +#ifndef PACKETIZER_H
It is now only used for SRT code. The class is quite generic. We could have other use. For example, I am fine if you think it is good to move it to SRT code. However imho it would be good to not include it inside the outgoing stream code. As at least this is easy for testing.

2024-10-03 12:40 UTC, harryz2000 commented on include/Packetizer.h
> + * @tparam T The message type. It must be derived from Serializable.
Initial implementation doesn't have this requirement. But yes, it could be changed to use Serializable instead.

2024-10-03 12:41 UTC, harryz2000 commented on include/Packetizer.h
> +	virtual size_t GetNextPacket(BufferWritter& writer)
OK

2024-10-04 07:40 UTC, murillo128 commented on include/Packetizer.h
> +#ifndef PACKETIZER_H
me can keep the class in the media-server-src but moving it to the mpegts dir and renaming to something a bit more verbose, we already have RTPPacketizers, so could be easy to confuse them

2024-10-04 08:07 UTC, murillo128 commented on include/Serializable.h
> +class Serializable
shouldn't only the top level messages (i.e. PESMessage, PSIMessage) derive from `Serializable`  calling `virtual` methods hurts performance and prevents inlining

2024-10-08 04:47 UTC, harryz2000 commented on include/Serializable.h
> +class Serializable
Can you clarify a bit? Do you mean make all the mpegts fields, such as mpgets::Header, not derived from Serializable? Or the PESMessage child classes, such as H26xPESMessage, not derived from Serializable? PESMessage is in another PR. But not sure what do you mean top level.

For the fields, it doesn't need to inherit from Serializable, as there is no need for inheritance there. I can remove it. For the message, I wouldn't think the inheritance would impact performance a lot as the function is only called per message, which means a frame. We could use templates instead of inheritance to get rid of the virtual functions. Do you think we could go that way or any other thoughts?

2024-10-08 04:55 UTC, harryz2000 commented on include/Serializable.h
> +class Serializable
Removed the Serialzable inheritance from fields now.

2024-10-08 11:13 UTC, murillo128 commented on src/mpegts/Packetizer.h
> +class MessagePacketizer
rename filename to match class name please

2024-10-08 11:16 UTC, murillo128 requested changes
almost lgtm, minor changes required though

2024-10-08 11:16 UTC, murillo128 commented on src/FrameDelayCalculator.cpp
> - * @return The timestamp basing on the target clock rate
does this needs a rebase?

2024-10-08 11:16 UTC, murillo128 commented on src/mpegts/mpegtscrc32.cpp
> +static const uint32_t CrcTable[256] = {
is this crc32 different than the one already available  https://github.com/medooze/media-server/blob/c611ec586d83527ebcba21ddb598a018d13cf2c4/include/crc32calc.h#L16 ?

2024-10-08 11:16 UTC, murillo128 commented on src/mpegts/psi.h
> +#include "mpegts.h"
do we need this include here?

2024-10-08 22:32 UTC, harryz2000 commented on src/mpegts/mpegtscrc32.cpp
> +static const uint32_t CrcTable[256] = {
Yes. This one is different. I tried the existing ones and they didn't work.

2024-10-08 22:52 UTC, harryz2000 commented on src/mpegts/psi.h
> +#include "mpegts.h"
No need. removed.

2024-10-08 22:53 UTC, harryz2000 commented on src/mpegts/Packetizer.h
> +class MessagePacketizer
done

2024-10-08 23:22 UTC, harryz2000 commented on src/FrameDelayCalculator.cpp
> - * @return The timestamp basing on the target clock rate
OK. This is due to the PR I created was actually merging to this branch rather than the master. I can cherry pick the commit to master and do the rebase.

2024-10-09 06:43 UTC, murillo128 commented on src/mpegts/mpegts.h
> +	// Serializable overrides
remove outdated comments please

2024-10-09 06:49 UTC, murillo128 commented on src/mpegts/Serializable.h
> +#define SERIALIZABLE_H
are we using this interface anymore? if not, please remove

2024-10-09 07:11 UTC, harryz2000 commented on src/mpegts/Serializable.h
> +#define SERIALIZABLE_H
It is only used in tests. Moved there for convenience.

2024-10-09 07:29 UTC, harryz2000 commented
Will merge this shortly as per discussion.

2024-10-09 07:33 UTC, merged