Fix mp3 decoding and add unit test
medooze/media-server pull request #356
Opened 2024-10-03 21:37 UTC by amaha877

2024-10-04 07:27 UTC, murillo128 requested changes

2024-10-04 07:27 UTC, murillo128 commented on src/AudioDecoderWorker.cpp
> +				if (frame->HasCodecConfig())
as we pass now the full frame to the decoder, could we move the call the SetConfig to the decoder itself?

2024-10-07 18:49 UTC, amaha877 commented on src/AudioDecoderWorker.cpp
> +				if (frame->HasCodecConfig())
Not sure if i follow completely. Isn't that what we're doing with
`auto mp3 = static_cast<MP3Decoder*>(audioDecoder.get());
//Set config there
						mp3->SetConfig(frame->GetCodecConfigData(), frame->GetCodecConfigSize());`

2024-10-07 21:40 UTC, murillo128 commented on src/AudioDecoderWorker.cpp
> +				if (frame->HasCodecConfig())
we are doing it on the worker, my suggestion was to move it to inside the Mp3/AacDecoder::Decode()  method instead.

2024-10-08 01:29 UTC, yezhan10 commented on src/AudioDecoderWorker.cpp
> +				if (frame->HasCodecConfig())
if we want to use config that is stored in audio frame, guess a change is required to make in MPEGTSMPEG1AudioStream and MPEGTSMPEG2AudioStream:
from 	`frame.SetCodecConfig(reader.PeekData(), 4);` to ` frame.SetCodecConfig(mp3.PeekData(), 4);`
Also if possible, we also need to convert the clockrate from 90000 to sample rate of incoming audio.

2024-10-09 16:24 UTC, amaha877 commented on src/AudioDecoderWorker.cpp
> +				if (frame->HasCodecConfig())
Sounds good. I moved the `setConfig()` call inside the decoders. We can address the mp3 config parsing in another PR.

2024-10-09 17:42 UTC, yezhan10 commented on src/mp3/MP3Decoder.cpp
> +		SetConfig(audioFrame->GetCodecConfigData(), audioFrame->GetCodecConfigSize());
Should we move this setConfig() to private member function if we intend to only allow decoder to modify it's config data?

2024-10-09 18:20 UTC, amaha877 commented on src/mp3/MP3Decoder.cpp
> +		SetConfig(audioFrame->GetCodecConfigData(), audioFrame->GetCodecConfigSize());
I thought about that but figured it would be better to keep it consistent with AACDecoder because the AACDecoder offers a `void SetAACConfig(const uint8_t* data,const size_t size);` public method that is exposed via SWIG in the audioCodecsNode. Perhaps someday we might need it exposed for MP3 as well?

2024-10-10 00:48 UTC, yezhan10 commented on src/mp3/MP3Decoder.cpp
> +		SetConfig(audioFrame->GetCodecConfigData(), audioFrame->GetCodecConfigSize());
yeah it makes sense, i got impression that this SetAACConfig() is never being used even though AudioDecoder.js has a function uses this function, but not sure what's it for. For consistency, guess we can leave it as it is for now.

2024-10-10 07:00 UTC, murillo128 commented on src/mp3/MP3Decoder.cpp
> +		SetConfig(audioFrame->GetCodecConfigData(), audioFrame->GetCodecConfigSize());
aac allows signaling config out of band (via sdp for example), that's why it is public.

2024-10-10 07:00 UTC, murillo128 approved these changes
lgtm

2024-10-10 07:00 UTC, merged