Dev/amaha/DIOS-7241 implement VUI/HRD parsing
medooze/media-server pull request #365
Opened 2024-10-21 22:35 UTC by amaha877

Implement VUI and HRD parsing in the media server. This is required for the CENC node. Currently it is using shaka to do the parsing. Also adds unit tests.

2024-10-21 22:37 UTC, amaha877 commented
Not sure what the best way to review this. My approach was to implement with libavcodec as reference code and the H264 spec open side by side

2024-10-22 07:46 UTC, murillo128 requested changes

2024-10-22 07:46 UTC, murillo128 commented on src/h264/h264.h
> +static constexpr uint8_t EXTENDED_SAR = 255;
make CamelCase please

2024-10-22 07:46 UTC, murillo128 commented on src/h264/h264.h
> +	struct vuiParameters;
Make CamelCase

2024-10-22 07:46 UTC, murillo128 commented on src/h264/h264.h
> +	bool ParseHRDParams(RbspBitReader &r, hrdParameters &hrd)
move Parse to  `VuiParameters` struct

2024-10-22 07:46 UTC, murillo128 commented on src/h264/h264.h
> +				cpb_cont_minus1_valid = false;
remove

2024-10-22 07:46 UTC, murillo128 commented on src/h264/h264.h
> +		catch(const std::exception& e)
don't catch exceptions, let calling class deal with it

2024-10-22 07:46 UTC, murillo128 commented on src/h264/h264.h
> +				Warning("-H264SeqParameterSet::ParseHRDParameters() Invalid cpb_cnt_minus1 %u. Not in Range [%u, %u]\n",
should we throw instead?

2024-10-22 07:46 UTC, murillo128 commented on src/h264/h264.h
> +	bool DecodeVuiParameters(RbspBitReader &r)
move to `VuiParameters`

2024-10-22 07:46 UTC, murillo128 commented on src/h264/h264.h
> +					Warning("-H264SeqParameterSet::DecodeVuiParameters() Illegal aspect ratio\n");
throw or return error

2024-10-22 07:46 UTC, murillo128 commented on src/h264/h264.h
> +				vuiParams.sar_width = 0;
use `std::optional` instead of 0 for optional values

2024-10-22 07:46 UTC, murillo128 commented on src/h264/h264.h
> +					Warning("-H264SeqParameterSet::DecodeVuiParameters() Invalid chroma sample_loc_type_top_field %u. Not in Range [%u, %u]\n",
return false

2024-10-22 07:46 UTC, murillo128 commented on src/h264/h264.h
> +					Warning("-H264SeqParameterSet::DecodeVuiParameters() Invalid chroma sample_loc_type_bottom_field %u. Not in Range [%u, %u]\n",
return false

2024-10-22 07:46 UTC, murillo128 commented on src/h264/h264.h
> +		for (uint32_t SchedSelIdx = 0; SchedSelIdx <= hrd.cpb_cnt_minus1; SchedSelIdx++)
make camelCase

2024-10-22 07:46 UTC, murillo128 commented on src/h264/h264.h
> +	void DumpHrdParams(const hrdParameters &hrd) const
move to `HdrParameters`

2024-10-22 07:46 UTC, murillo128 commented on src/h264/h264.h
> +		Debug("\t\taspect_ratio_info_present_flag=%u\n", vuiParams.aspect_ratio_info_present_flag);
move to  `VuiParameters`

2024-10-22 07:46 UTC, murillo128 commented on src/h264/h264.h
> +    	uint32_t      overscan_appropriate_flag = 0;
please use tabs and not spaces for ident

2024-10-22 07:46 UTC, murillo128 commented on test/unit/TestCommon.h
> +#include <include/gmock/gmock.h>
what do we need `gmock` for?

2024-10-22 18:06 UTC, amaha877 commented on src/h264/h264.h
> +		catch(const std::exception& e)
I generally agree with that but i was just making it consistent with the master `Decode()` function which catches failures.

2024-10-22 18:07 UTC, amaha877 commented on src/h264/h264.h
> +				cpb_cont_minus1_valid = false;
we are using the bool here:
`if (cpb_cont_minus1_valid)
			{
				for (uint32_t SchedSelIdx = 0; SchedSelIdx <= hrd.cpb_cnt_minus1; SchedSelIdx++)
				{
					hrd.bit_rate_value_minus1.push_back(r.GetExpGolomb());
					hrd.cpb_size_value_minus1.push_back(r.GetExpGolomb());
					hrd.cbr_flag.push_back(r.Get(1));
				}
			}`

2024-10-22 18:10 UTC, amaha877 commented on test/unit/TestCommon.h
> +#include <include/gmock/gmock.h>
gmock provides more matching functionality for `EXPECT` statements. For example:

`EXPECT_THAT(spsParser.vuiParams.nal_hrd_parameters.bit_rate_value_minus1,
				::testing::ElementsAreArray({78124}));`

2024-10-22 19:28 UTC, amaha877 commented on src/h264/h264.h
> +		catch(const std::exception& e)
Oh i see what you're saying. The caller is just the `Decode()` function which already is in a try catch block so we don't need to do that in the vui and hrd functions

2024-10-22 19:35 UTC, murillo128 commented on test/unit/TestCommon.h
> +#include <include/gmock/gmock.h>
thanxs!

2024-10-22 20:08 UTC, amaha877 commented on src/h264/h264.h
> +				cpb_cont_minus1_valid = false;
Actually I will remove it since i'm going to return `false` on out of bounds/invalid values for fields.

2024-10-22 22:50 UTC, eck1001 commented on test/unit/TestH26xSPS.cpp
> +	const std::vector<BYTE> VuiData = {
Where does this data come from?

2024-10-22 22:52 UTC, eck1001 commented on test/unit/TestH26xSPS.cpp
> +	EXPECT_EQ(0, SpsParser.frame_cropping_flag);
Is there a spec or document that explains what the expected sps values should be?

2024-10-23 07:19 UTC, murillo128 requested changes

2024-10-23 07:19 UTC, murillo128 commented on src/h264/h264.h
> +				if (!VuiParams.DecodeVuiParameters(r))
object attributes are camelCase

2024-10-23 07:19 UTC, murillo128 commented on src/h264/h264.h
> +				if (!VuiParams.DecodeVuiParameters(r))
consider using a different pattern:

make `vuiParams` optional
```
class H264SeqParameterSet
{
private:
    std::optional<VuiParameters> vuiParams;
}
```

and then make the flag local
```` 
                       bool vui_parameters_present_flag = r.Get(1);
			if (vui_parameters_present_flag) 
			{
                               VuiParams vuiParams;
				if (!vuiParams->Decode(r))
                                      return false; 
                                this->vuiParams = vuiParams;
                         }
```

2024-10-23 07:19 UTC, murillo128 commented on src/h264/h264.h
> +		bool ParseHRDParams(RbspBitReader &r)
keep naming consistency
```suggestion
		bool Decode(RbspBitReader &r)
```

2024-10-23 07:19 UTC, murillo128 commented on src/h264/h264.h
> +		void DumpHrdParams() const
keep naming consistency
```suggestion
		void Dump() const 
```

2024-10-23 07:19 UTC, murillo128 commented on src/h264/h264.h
> +		bool DecodeVuiParameters(RbspBitReader &r)
keep naming consistency
```suggestion
		bool Decode(RbspBitReader &r)
```

2024-10-23 07:19 UTC, murillo128 commented on src/h264/h264.h
> +		void DumpVuiParams() const
keep naming consistency
```suggestion
		void Dump() const
```

2024-10-23 16:50 UTC, amaha877 commented on test/unit/TestH26xSPS.cpp
> +	const std::vector<BYTE> VuiData = {
I got the test cases from this other public repo
https://github.com/chemag/h264nal

2024-10-23 16:51 UTC, amaha877 commented on test/unit/TestH26xSPS.cpp
> +	EXPECT_EQ(0, SpsParser.frame_cropping_flag);
The repo above helps but i also double checked with ffprobe

2024-10-24 06:49 UTC, murillo128 requested changes
almost lgtm, some minor changes

2024-10-24 06:49 UTC, murillo128 commented on src/h264/h264.h
> +	struct VuiParameters;
no need for forward declarations, please move the structs to the top of the class.

2024-10-24 06:49 UTC, murillo128 commented on src/h264/h264.h
> +			vui_parameters_present_flag = r.Get(1);
no need to keep the flag now as the class now has the `std::optional`
```suggestion
			bool vui_parameters_present_flag = r.Get(1);
```

2024-10-24 06:49 UTC, murillo128 commented on src/h264/h264.h
> +	bool			vui_parameters_present_flag = false;
remove

2024-10-24 18:14 UTC, amaha877 commented on src/h264/h264.h
> +	struct VuiParameters;
Okay, the only reason I did that was to reduce the diff :) Anyway, I will move the structs up.

2024-10-24 18:18 UTC, amaha877 commented on src/h264/h264.h
> +			vui_parameters_present_flag = r.Get(1);
Hmm, I see that in most other places in the codebase we do keep the bool `xxxx_present_flag` . My suggestion would be to retain the bool flags as long as it is a field that is referenced by the spec. Wdyt?

2024-10-25 06:48 UTC, murillo128 requested changes

2024-10-25 06:48 UTC, murillo128 commented on src/h264/h264.h
> +				Debug("\t\tsar_width=%u\n", sar_width);
```suggestion
				Debug("\t\tsar_width=%u\n", sar_width.value());
```

2024-10-25 06:48 UTC, murillo128 commented on src/h264/h264.h
> +				Debug("\t\tsar_height=%u\n", sar_height);
```suggestion
				Debug("\t\tsar_height=%u\n", sar_height.value());
```

2024-10-25 06:52 UTC, murillo128 commented on src/h264/h264.h
> +			vui_parameters_present_flag = r.Get(1);
i want to change the codebase to use this pattern intstead, so we don't have to do

```
 if (vui_parameters_present_flag && vuiParameters) 
```

2024-10-28 20:48 UTC, merged