split nalu to equal rtp packet size
medooze/media-server pull request #367
Opened 2024-10-23 17:36 UTC by yezhan10

2024-10-24 06:43 UTC, murillo128 requested changes

2024-10-24 06:43 UTC, murillo128 commented on src/h264/H26xPacketizer.cpp
> +	auto numPackets = nal.GetLeft() / (RTPPAYLOADSIZE - fuPrefixSize) + 1;
wouldn't this give an incorrect packet count if mod is 0? i.e. if `nal.GetLeft()` is `(RTPPAYLOADSIZE - fuPrefixSize)`

`auto numPackets = (RTPPAYLOADSIZE - fuPrefixSize) / (RTPPAYLOADSIZE - fuPrefixSize) + 1; ` is 2 an not 1.


```suggestion
	auto numPackets = std::ceil(nal.GetLeft() / (RTPPAYLOADSIZE - fuPrefixSize));
```

2024-10-24 06:43 UTC, murillo128 commented on src/h264/H26xPacketizer.cpp
> +	auto numPackets = nal.GetLeft() / (RTPPAYLOADSIZE - fuPrefixSize) + 1;
could you add a test for that as well?

2024-10-25 01:30 UTC, yezhan10 commented on src/h264/H26xPacketizer.cpp
> +	auto numPackets = nal.GetLeft() / (RTPPAYLOADSIZE - fuPrefixSize) + 1;
if `nal.GetLeft()` is `(RTPPAYLOADSIZE - fuPrefixSize)` then it can be fit into one single packet right? which would not need FU-A anymore I think. I can definitely add a test with nalUnitSize == 1200 bytes which is the min bytes for FU-A mode.

2024-10-25 06:13 UTC, murillo128 commented on src/h264/H26xPacketizer.cpp
> +	auto numPackets = nal.GetLeft() / (RTPPAYLOADSIZE - fuPrefixSize) + 1;
what I mean is that the code above will fail if mod=0

2024-10-29 07:30 UTC, murillo128 commented on test/unit/TestH26xRTPPacketization.cpp
> +        int mod = nalPayloadSize % expectedRTPPacekts;
please check `mod == 0`

2024-10-31 23:36 UTC, harryz2000 commented on src/h264/H26xPacketizer.cpp
> +	auto packetLen = nal.GetLeft() / numPackets;
should we check if numPackets == 0?

2024-10-31 23:38 UTC, harryz2000 commented on src/h264/H26xPacketizer.cpp
> +	uint32_t numPackets = std::ceil(static_cast<double>(nal.GetLeft()) / (RTPPAYLOADSIZE - fuPrefixSize));
Looks if mod != 0, one  more bytes will be added to each packet. Should we change this to?
```suggestion
	uint32_t numPackets = std::ceil(static_cast<double>(nal.GetLeft()) / (RTPPAYLOADSIZE - fuPrefixSize - 1));
```

2024-10-31 23:46 UTC, harryz2000 commented on src/h264/H26xPacketizer.cpp
> +	uint32_t numPackets = std::ceil(static_cast<double>(nal.GetLeft()) / (RTPPAYLOADSIZE - fuPrefixSize));
OK. Probably not an issue as you calculate packet len later.

2024-10-31 23:52 UTC, harryz2000 commented on test/unit/TestH26xRTPPacketization.cpp
> +        EXPECT_TRUE(mod!=0);
Can we change EXPECT_* to ASSERT_*? Mostly we shouldn't need to continue to run tests if previous check failed. Otherwise sometimes it might cause crash.

2024-10-31 23:53 UTC, harryz2000 commented on test/unit/TestH26xRTPPacketization.cpp
> +        EXPECT_TRUE(mod!=0);
Consider use:
```suggestion
        ASSERT_TRUE(0, mod);
```
It would give more useful info if it fails.

2024-10-31 23:59 UTC, harryz2000 commented on src/h264/H26xPacketizer.cpp
> +	int mod = nal.GetLeft() % numPackets;
I think it would be good if we have test cases for following scenarios.
1. mod == 1
2. mod == (packetLen - 1)
3. mod == 0
You probably have added. Just wanted to confirm as I am not sure value of each constants.

2024-11-04 17:12 UTC, yezhan10 commented on src/h264/H26xPacketizer.cpp
> +	auto packetLen = nal.GetLeft() / numPackets;
i dont think it's required, since we only split nalu if the size is greater than 1200 bytes

2024-11-06 07:40 UTC, murillo128 approved these changes
lgtm

2024-11-07 02:17 UTC, merged