fix: [DIOS-7649] Add SOREUSEPORT option to bound TCP sockets to workon BSD systems
medooze/media-server pull request #389
Opened 2024-11-14 05:50 UTC by bcostdolby

…on BSD

2024-11-14 17:25 UTC, eck1001 requested changes

2024-11-14 17:25 UTC, eck1001 commented on src/ws/websocketserver.cpp
> +	int result = setsockopt(server, SOL_SOCKET, SO_REUSEADDR, &optval, sizeof(optval));
change-request: Lines 94-97 were these suppose to be deleted? They look like duplicates.

2024-11-14 17:26 UTC, eck1001 commented on src/rtmp/rtmpserver.cpp
> +	// See https://stackoverflow.com/questions/14388706/how-do-so-reuseaddr-and-so-reuseport-differ
🎉: love the context notes -- thanks - BSD sockets... what a world

2024-11-17 23:55 UTC, harryz2000 commented
lgtm

2024-11-17 23:55 UTC, harryz2000 approved these changes

2024-11-18 01:00 UTC, mildsunrise commented
wait, do we want to make medooze work in systems other than Linux? we abandoned that path quite some time ago, and I'm not sure it's a good idea to retake it...

2024-11-18 01:09 UTC, harryz2000 commented
I think this is for Linux over Docker. @bcostdolby can confirm.

2024-11-18 01:19 UTC, bcostdolby commented
> wait, do we want to make medooze work in systems other than Linux? we abandoned that path quite some time ago, and I'm not sure it's a good idea to retake it...

I am just trying to make it work in docker on the m3. It is using rosetta to emulate so is not a arm arch running but intel. It works fine but there are some minor behaviour differences and IMO using SO_REUSEPORT is correct anyway.

2024-11-18 06:20 UTC, merged

2024-11-19 21:54 UTC, mildsunrise commented
I am still a bit confused, doesn't docker desktop start a Linux VM and run docker deamon there? why would this change be needed for such a setup, if it's running inside a Linux VM? :o

2024-11-19 23:37 UTC, eck1001 commented
Docker linux containers still share the host kernel and SO_REUSEPORT is a feature implemented at the kernel level